aws/graph-explorer

packages/graph-explorer/src/connector/gremlin/mappers/parsePropertiesValues.ts

*Description of changes:* 
If graph vertices has no property then the parsing fails. With this fix, we are defaulting to empty object if no properties are present. [Similar code](https://github.com/aws/graph-explorer/blob/637d26b21f99e387bee3ab8b3a1e193b91d89202/packages/graph-explorer/src/connector/gremlin/mappers/parseEdgePropertiesValues.ts#L8) is already present for parsing edge property values.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Default to empty object when vertices has no property

---

packages/graph-explorer-proxy-server/node-server.js

Addresses credential refresh when credentials are either expired or undefined. Currently this is done blindly and in the case of any error in the response, it will attempt a credential refresh, retry the request and if the retry also fails, log the status code causing the failure.

Fix credential refresh bug

---

additionaldocs/development.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/graph-explorer/src/@types/typings.d.ts
packages/graph-explorer/src/components/Workspace/Workspace.styles.ts
packages/graph-explorer/src/components/Workspace/components/WorkspaceTopBar.tsx
packages/graph-explorer/src/components/Workspace/components/WorkspaceTopBarVersion.tsx
packages/graph-explorer/src/core/ThemeProvider/themes/dark.ts
packages/graph-explorer/src/core/ThemeProvider/themes/light.ts
packages/graph-explorer/src/core/ThemeProvider/types.ts
packages/graph-explorer/src/workspaces/common/TopBarWithLogo.tsx
packages/graph-explorer/vite.config.ts

*Issue 77*
*Description of changes:*
- Display the version number in the top bar of all workspaces.
- The version number is extracted from the package.json version number and injected into the application through the __GRAPH_EXP_VERSION__ variable, which can be globally accessed by the application components.

Display GraphExplorer version in client UI

---

Changelog.md
Dockerfile
README.md
additionaldocs/development.md
docker-entrypoint.sh

Removed self-signed SSL cert creation from Dockerfile and created a new entrypoint script for certs to be created when the container is launched.  This removes the need for a user to build a new container image for each deployment and allows them to set the hostname used by the SSL cert upon launching the container using a `HOST` environment variable.
Updated README.md to include the updated steps for container image build and launching a new container.  Also added a new Troubleshooting section to address common issues seen by users attempting to launch graph-explorer.

Moving self-signed SSL cert creation to docker entrypoint script.

---

.github/workflows/build_docker.yml

- Updating Docker auto-publish workflow to deploy to the new ECR Public Gallery repository at: https://gallery.ecr.aws/neptune/graph-explorer
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Update build_docker.yml for ECR Public deployments

---

README.md

- Updating Connections UI documentation to use the correct protocol/port for the proxy endpoint. Attempting to use port 8182 results in a `ERR_CONNECTION_TIMED_OUT` exception during synchronization.

Revise connection docs for single server update

---

packages/graph-explorer-proxy-server/node-server.js

Changes the error code provided when the credentials are undefined after refresh due to not having an IAM role attached.

Change no IAM role attached error code

---

packages/graph-explorer/src/connector/gremlin/templates/edgesSchemaTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/verticesSchemaTemplate.ts
packages/graph-explorer/src/utils/sanitizeText.ts

Issue #57 and #83 
**Issue:**
Before being passed to the react logic, requests related to the schema synchronization on the connection page, would go through a filter that would go through a replace operation that would remove spaces. This removes the ability to use vertices or edges with a space in the label name via gremlin queries.
**Description of Changes:**
- Removes the regex replacement in the `packages/graph-explorer/src/connector/gremlin/templates/verticesSchemaTemplate.ts` file to avoid replacing whitespace that actually need to be urlEncoded in gremlin requests.
- Removes a line in `packages/graph-explorer/src/utils/sanitizeText.ts` that was causing any string of the format {string}{number} to be split into {string} {number}. This caused labels such as "Node1" to be considered …

Fix for database synchronization error caused by white spaces in the labels for gremlin requests

---

packages/graph-explorer-proxy-server/node-server.js
packages/graph-explorer/src/connector/AbstractConnector.ts
packages/graph-explorer/src/connector/gremlin/GremlinConnector.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchSchema.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchVertexTypeCounts.ts
packages/graph-explorer/src/connector/gremlin/templates/vertexTypeCountTemplate.ts
packages/graph-explorer/src/connector/gremlin/types.ts
packages/graph-explorer/src/connector/sparql/SPARQLConnector.ts
packages/graph-explorer/src/connector/sparql/queries/fetchClassCounts.ts
packages/graph-explorer/src/connector/sparql/queries/fetchSchema.ts
packages/graph-explorer/src/connector/sparql/templates/classWithCountsTemplates.ts
packages/graph-explorer/src/connector/sparql/types.ts
packages/graph-explorer/src/core/ConfigurationProvider/ConfigurationProvider.tsx
packages/graph-explorer/src/core/ConfigurationProvider/types.ts
packages/graph-explorer/src/core/StateProvider/configuration.ts
packages/graph-explorer/src/core/StateProvider/schema.ts
packages/graph-explorer/src/hooks/useEntitiesCounts.ts
packages/graph-explorer/src/hooks/useSchemaSync.ts
packages/graph-explorer/src/hooks/useUpdateSchema.ts
packages/graph-explorer/src/hooks/useUpdateVertexTypeCounts.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionData.tsx
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

The main aim of this PR is to reduce the synchronization time of the schema by using Neptune Summary API if it is available.
- `fetchSchema` process tries to fetch some data, using the Summary API, related to the database structure:
-  vertices types (classes),
-  edges types (predicates),
-  total number of vertices (total number of subjects),
-  and total number of edges (total number of quads)
- If the above data is available, use them to fetch the vertices and edges attributes. By using the Summary API, the time of inferring the schema will be decreased. However, it does not return how many vertices or edges we have by type. So we speed up the process but lose the counts by type.
- If the Summary API is not available, the `fetchSchema` fallbacks to the previous …

Use the Summary API to improve the schema synchronization performance

---

Dockerfile

Issue #, if available: #103
Changes the Dockerfile to perform all the `RUN` commands on one line thus reducing the number of layers and reducing the overall size of the Docker image by 1gb when built on Ubuntu. 1.67gb --> 675mb

Reduce size of Docker image #103

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Bump package version to 1.2.0

Release 1.2.0

---

packages/graph-explorer-proxy-server/node-server.js

Proxy server is currently serving static files on `/explorer`. 
Serving static files through express is  broken when using a custom .env value in `GRAPH_EXP_ENV_ROOT_FOLDER`

Proxy server serving should match GRAPH_EXP_ENV_ROOT_FOLDER

---

packages/graph-explorer/src/connector/gremlin/queries/keywordSearch.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.ts

Issue #107:
Sets id search to true in the request and also by default for any gremlin connection so that searches now include the vertex ids in the possible parameters that an input string can match. 
Tested via a local build attempting to search on an id and received the expected node.

Adds id search by default to gremlin keyword search

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/node-server.js
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Fixed a bug where requests from Explorer to non IAM-enabled Neptune endpoints would fail in cases where HTTPS was enabled on the proxy, with the error: `Hostname/IP does not match certificate's altnames`.
- Bump Graph Explorer version to 1.3.1 for patch release

Fix proxy issue with non-IAM connections

---

Changelog.md
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.tsx

Issue #, if available: #165
- Fixed a bug where the keyword search handler failed to pass sufficient PaginationOptions to the details preview renderer  upon node selection.

Fixed search UI crashing on node select/preview

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.ts

Issue #, if available: #168
- Restricted Gremlin/openCypher keyword search matches on node ID to cases where the user has selected `Attribute`:`All`.

Exclude ID from unrelated node attribute search in Gremlin/openCypher

---

Changelog.md
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/hooks/useFetchNode.ts
packages/graph-explorer/src/modules/GraphViewer/useNodeDrop.ts
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.tsx
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.ts

Issue #, if available: #172
- Added a `Limit Neighbors?` checkbox element in the search UI. By default, this option will be checked, allowing for a maximum of 500 neighbors to be retrieved for each vertex added to the canvas. If unchecked by the user, no limit will be imposed on inserted vertices.
Example Usage:

Add toggle option for limit on retrieved vertex neighbors

---

.github/workflows/build_docker.yml
Changelog.md
packages/graph-explorer/src/connector/AbstractConnector.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/hooks/translations/gremlin-translations.json
packages/graph-explorer/src/hooks/translations/openCypher-translations.json
packages/graph-explorer/src/hooks/translations/sparql-translations.json
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.tsx
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.ts

Issue #, if available: #149
- Added a new `Match Precision` drop-down field to the keyword search interface. Users can now choose to match using options:
- a) `Exact`: Node must have an attribute value that matches the search keyword exactly. 
- b) `Partial`: Node has an attribute value containing the search keyword. This option is identical to the old search behavior, and will remain as the default option.
Example usage:
- EDIT: `Fuzzy` option has been renamed to `Partial`.

Add Match Precision option to keyword search

---

.github/workflows/build_docker.yml
Changelog.md
Dockerfile
README.md
packages/graph-explorer-proxy-server/node-server.js
packages/graph-explorer/.env
packages/graph-explorer/src/index.tsx
pnpm-lock.yaml
process-environment.sh

- Added provisions to allow Graph Explorer to run inside and be accessible from a SageMaker Notebook instance.
- Modified ECR deployment workflow to push an additional SageMaker-compatible Docker image on commit/release.

Add SageMaker Notebook support

---

Changelog.md
additionaldocs/README.md
additionaldocs/sagemaker/README.md
additionaldocs/sagemaker/install-graph-explorer-lc.sh

- Added a sample lifecycle configuration script and documentation for usage on SageMaker Notebooks.

Add SageMaker documentation

---

pnpm-lock.yaml

Issue #, if available: CVE-2020-28500, CVE-2021-23337
- Cleaned up remaining usages of `lodash` v4.17.20 in the base pnpm lockfile, mainly from chain dependencies of `cytoscape-dagre`.

Bump lodash versions in lockfile

---

Changelog.md
Dockerfile

- Migrating the Dockerfile off AL2 in favor of AL2022 platform, due to standing [vulnerabilities](https://hub.docker.com/layers/library/amazonlinux/2/images/sha256-993d82940dba5370065dd5afb99fab56cdaf9f7b88800e88ddbd622678a6d3ea?context=explore) in the former.

Update Dockerfile base image to AL2022

---

Changelog.md
pnpm-lock.yaml

Issue #, if available: https://github.com/aws/graph-explorer/security/dependabot/3
- Regenerated base lockfile to remove some references of type definitions package `@types/semver` to a vulnerable version of `semver`.

Bump @types/semver to 7.5.2 in lockfile

---

.github/workflows/build_docker.yml
additionaldocs/sagemaker/install-graph-explorer-lc.sh

Issue #, if available:
This Pull Request updates the tagging convention used in our GitHub Actions workflow for building and pushing Docker images. The `latest` tag is replaced with `latest-SNAPSHOT` to provide a clearer distinction between stable releases and the latest development snapshot of the ERC images. 
This naming convention aligns with common practices, making it easier to identify the nature of each image and ensuring a more organized and predictable tagging structure. By adopting this change, we are moving towards a more descriptive and developer-friendly tagging system for our Docker image repository.

Update Docker Tag to latest-SNAPSHOT for ERC Images

---

additionaldocs/sagemaker/install-graph-explorer-lc.sh

- Changed the default behavior of the SageMaker Lifecycle to use the latest release version in ECR. Previously, the `latest-SNAPSHOT` auto-build version was the default.
- Improved user selection of specific ECR version tags via the `-ev`/`--explorer-version` parameter.

Improved version selection functionality in SageMaker Lifecycle

---

Changelog.md
packages/graph-explorer/src/components/Graph/hooks/useManageElementsSelection.ts
packages/graph-explorer/src/components/Graph/hooks/useManageStyles.ts

Issue #, if available: #179
- Fixed an issue where clicking on a node or edge in the graph would fail to result in the element remaining highlighted.

Persist node/edge highlighting on selection

---

Changelog.md
packages/graph-explorer/src/components/NotificationProvider/NotificationProvider.tsx

Issue #43
Issue #146 
By using the nodeRef object instead of findDOMNode, we've avoided the warning message and updated the code to use the recommended approach.

PR for Sometimes auto-expand fails with error & "findDOMNode is deprecated in StrictMode" error

---

Changelog.md
packages/graph-explorer-proxy-server/node-server.js
packages/graph-explorer/src/connector/gremlin/useGremlin.ts
packages/graph-explorer/src/connector/openCypher/useOpenCypher.ts
packages/graph-explorer/src/connector/sparql/useSPARQL.ts

Issue #, if available: #229 
- Added options for non IAM calls, to fix issues with openCypher and SPARQL connections using proxy server.
- Enforce JSON `Accept` header for SPARQL.

Refactor API request options for non IAM users, enforce JSON response format for SPARQL

---

.gitignore
Changelog.md
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/helpers.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/utils/escapeString.test.ts
packages/graph-explorer/src/utils/escapeString.ts
packages/graph-explorer/src/utils/index.ts

Issue #, if available:
Added escaping for search keywords. 
Searching for text containing quotes now works.

Escape search keyword

---

packages/graph-explorer-proxy-server/node-server.js
packages/graph-explorer/src/connector/openCypher/useOpenCypher.ts

- Refactored some Analytics connection sync logic: moved the service-based conditional to the OC connector, and added a separate ExpressJS route for the Analytics summary endpoint, matching the actual Neptune endpoint. This should help prevent some confusion when debugging service-specific sync issues.

Refactor PG summary proxy routes

---

README.md
packages/graph-explorer/src/index.tsx
process-environment.sh

- Fixed generation of default connection profiles via Docker run arguments when using Neptune Analytics..

Fix Neptune Analytics default connections

---

packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.styles.ts
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.tsx

Issue #, if available: #261
- Arrange layout using flex and gaps
- Use `Button` component instead of `IconButton`
**Before**
> **NOTE:** The "Clear Selected" button is currently in the hover state in this screenshot, showing the incorrect behavior it has today compared to other buttons.
**After**

Fix search bottom bar UI

---

packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/useSPARQL.ts
packages/graph-explorer/src/core/ConnectorProvider/ConnectorProvider.tsx
packages/graph-explorer/src/core/ConnectorProvider/types.ts
packages/graph-explorer/src/hooks/useExpandNode.ts

- Ran `pnpm run types:check`, which found some issues
- Pass `exactMatch` to `keywordSearchBlankNodesIdsTemplate`
- Remove some unnecessary explicit type casting
- Expose `Explorer` type and ensure all explorer conform
- Fix `fetchNeighbors` result type in SPARQL
- Fix many type issues in `useExpandNode`

Fix all TypeScript issues

---

packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplateEdges.ts

- Remove unnecessary quote escapes when using string literals
- Remove unused `offset` parameter in `oneHopTemplate`

Fix ESLint issues

---

packages/graph-explorer-proxy-server/node-server.js

Issue #, if available: #265
Fixes an issue where cancelling a query is not supported by the database server and the Graph Explorer server will crash.
Other changes:
- Skip logging about "max retries reached" if max retries is `1`
- Move error JSON deserialization after log statements in case it fails
- Log out response status and text on failed requests
- Log failed cancellations as warnings

Cancel queries gracefully

---

packages/graph-explorer/src/connector/sparql/templates/keywordSearch/helpers.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchTemplate.test.ts

The "__all" predicates filter was being applied to the SPARQL query when chosen. It wasn't causing any harm, but it shouldn't be there.
This PR removes it and updates the tests.

Remove “__all” from query in SPARQL

---

Changelog.md
packages/graph-explorer-proxy-server/package-lock.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer-proxy-server/pnpm-lock.yaml
packages/graph-explorer/pnpm-lock.yaml
pnpm-lock.yaml

Issue #, if available: CVE-2024-29041
- Updating proxy server to Express 4.19.2.

Bump express to 4.19.2

---

packages/graph-explorer-proxy-server/node-server.js
packages/graph-explorer/src/connector/useGEFetch.ts
packages/graph-explorer/src/hooks/useSchemaSync.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearchQuery.ts
packages/graph-explorer/src/utils/createDisplayError.test.ts
packages/graph-explorer/src/utils/createDisplayError.ts

Improves the error handling within Graph Explorer and the proxy server in various ways.
- Add `createDisplayError()` function to map errors to friendly errors that can be displayed to the user (this will grow over time)
- Use `createDisplayError()` in schema sync and keyword search
- Check if `response.ok` for any `useGEFetch()` requests and throw an error if it is not
- Attempt to decode error response bodies in a safe way
- Move routes out of unnecessary async closure
- Remove duplicate `app.use(errorHandler)`
- Send error responses from the remote database through the proxy back to the client with minimal changes
- When reviewing the code it will be useful to turn on the "ignore whitespace changes" feature in GitHub
- Added tests for errors I know about
- Disconnect VPC or wifi to get …

Better error handling

---

.github/pull_request_template.md
package.json

Updates the GitHub pull request template to have an easier to read formatting and include helpful comments for open source contributors.
The format was heavily inspired from the [nodejs.org GitHub repository template](https://github.com/nodejs/nodejs.org/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1), which provides a great foundation to build upon.
The new format will look like this PR description.
- Verify comments match the language desired
- Verify links navigate to the right place
- Ensure all information desired from a PR is mentioned
- Ensure format is easy to understand
N/A

Update pull request template

---

packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.styles.ts

Removes the background color on the results count text. This makes the background clear which allows the hover color to come through.
1. Open search panel to get results
2. Close search panel
3. See non-hover result count in search bar
4. Hover over to see hover state
Fixes #291

Fix search bar hover color

---

README.md
packages/graph-explorer/src/connector/gremlin/useGremlin.ts
packages/graph-explorer/src/connector/openCypher/useOpenCypher.ts
packages/graph-explorer/src/connector/sparql/useSPARQL.ts
packages/graph-explorer/src/connector/useGEFetch.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/connector/utils/anySignal.ts
packages/graph-explorer/src/core/ConfigurationProvider/types.ts
packages/graph-explorer/src/core/ConnectorProvider/ConnectorProvider.tsx
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx

- Removed local fetch caching logic
- Removed fetch caching configuration in connection
When the change was made to use POST for database queries (PR #206), it completely broke the local fetch caching that existed before. This makes the caching logic and configuration irrelevant and essentially dead code.
If we desire client side caching for network calls, we should lean on [React Query caching](https://tanstack.com/query/v4/docs/framework/react/guides/caching), which is already being used by Graph Explorer in some ways. Removing the custom client side caching makes this transition simpler when it comes time.
> \[!IMPORTANT]\
> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Remove fetch caching

---

packages/graph-explorer/jest.config.ts
packages/graph-explorer/package.json
packages/graph-explorer/src/modules/GraphViewer/renderNode.test.ts
packages/graph-explorer/src/modules/GraphViewer/renderNode.tsx
packages/graph-explorer/src/modules/GraphViewer/useGraphStyles.ts
packages/graph-explorer/src/setupTests.ts
packages/graph-explorer/src/utils/testing/randomData.ts
pnpm-lock.yaml

Fixes rendering of SVG images inside Cytoscape by wrapping performing the following modifications:
- Wrap the image SVG inside a custom SVG that conforms to Cytoscape rendering
- Uses `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>` at the top of the SVG string
- Hard codes the width and height to be `24`
- Ensures no `viewBox` at the outer level
- Change image SVG width and height to be `100%`
I took the opportunity to refactor the image logic in to a new function called `renderNode()` that has a test suite around it.
When setting the Cytoscape styles we also set the width and height of the node. I made sure the sizes match what was rendered before.
- I added the `randomData.ts` utility methods and `launch.json` from #280 since that hasn't been merged in yet
- I needed to use …

Fix custom SVG image rendering in graph

---

.github/workflows/build_docker.yml

Adds a step to the Docker workflow that will only be run when performing a release. This step will assign the `latest` tag to the build and push to the ECR repository.
I tested this by running the workflow locally using [act](https://nektosact.com/introduction.html). I created a public ECR repo in my AWS account and used my own secrets to perform the push.
I verified the new step will not run when `image_tag != 'release'`. I also verified that when it does run for a release it will push both the version tag and the `latest` tag. It will also push the SageMaker build with the `sagemaker-latest` tag. It will replace any existing `latest` tags with the new version.
Addresses #315

Add step to apply latest tag to docker image for releases

---

.vscode/settings.json
packages/graph-explorer/src/core/StateProvider/edges.ts
packages/graph-explorer/src/core/StateProvider/nodes.ts
packages/graph-explorer/src/hooks/useEntities.test.ts
packages/graph-explorer/src/utils/testing/randomData.ts

When entities are updated the logic in the setter was adding any node or edge types that were missing in the schema.
I've extended that logic to also add any attributes that are missing to the schema.
1. Add node to graph
2. Take note of existing attributes on node in details pane
3. Add property to node
```
g.V({Node ID}).property("added-prop", 123)
```
4. Clear graph
5. Add same node to graph
6. Notice new property in details pane
1. Add node to graph
2. Expand node and select edge
4. Take note of existing attributes on edge in details pane
3. Add property to edge
```
g.E({Edge ID}).property("added-prop", 123)
```
4. Clear graph
5. Add same node to graph
6. Expand
7. Select edge
8. Notice new property in details pane
- Addresses #355 
- Fixes #349

Ensure attributes are updated in schema when entities are updated

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Updates the feature request and bug issue templates to be a bit easier to use for the author and to have better formatting for the reader.
- Adds comment instructions for the author
- Adds additional formatting around titles
- Moves community note to bottom with more eye catching formatting
- Adds bug or feature request to the planning project automatically
Addresses #323

Improve the issue templates

---

packages/graph-explorer/package.json
packages/graph-explorer/src/core/ConnectedProvider/ConnectedProvider.tsx
packages/graph-explorer/src/hooks/useUpdateVertexTypeCounts.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearchQuery.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx
pnpm-lock.yaml

Updates the app to use TanStack Query v5 instead of React Query v3.
There were a decent number of breaking changes in these versions. Luckily, our app doesn't use React Query extensively, so there were only a few areas that needed close attention.
I also noticed and fixed a bug related to the vertex count logic. If you start on the connections screen and do a fresh sync you'll see the total node & edge counts. Then go in to one of the node types in the data explorer. When you come back to the connection screen the total counts are zeroed out.
This issue existed before the changes in this PR. But I fixed it anyway.
- Verify query and paging works in the data explorer
- Verify keyword search in graph explorer works
- Verify vertex counts are properly updated
- Addresses #334 
- Completes …

Update React Query v3 to TanStack Query v5

---

.github/pull_request_template.md

Updates the PR template to add a task to update the changelog file.

Add task to update changlog file

---

packages/graph-explorer/src/@types/entities.ts
packages/graph-explorer/src/connector/gremlin/mappers/detectIdType.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighbors.test.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighbors.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighborsCount.test.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighborsCount.ts
packages/graph-explorer/src/connector/gremlin/queries/keywordSearch.test.ts
packages/graph-explorer/src/connector/gremlin/queries/keywordSearch.ts
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/gremlin/useGremlin.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/sparql/mappers/mapRawResultToVertex.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/hooks/useExpandNode.ts
packages/graph-explorer/src/hooks/useFetchNode.ts
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/utils/testing/randomData.ts

This raw ID type map was being stored next to the connector state. It is a lookup for a vertex ID to its original type before it was mapped to a string.
Instead, I store this value on the `VertexData` instance. It should use the same or less memory and avoids all the strange state logic needed to maintain the map.
- Part 2 of #335

Refactor Connector Part 2 - raw ID type map

---

Changelog.md
packages/graph-explorer-proxy-server/node-server.js

The proxy server always assumes a response in JSON format, but that is not always the default response type.
This change makes it explicit that we want a JSON response by adding it to the headers:
```js
headers: {
"Content-Type": "application/x-www-form-urlencoded",
"Accept": "application/json"
},
```
- Verified with Neptune, all languages
- Verified with https://beta.sparql.swisslipids.org
- Addresses #393

Add "accept" header to requests from proxy server

---

Changelog.md
README.md
additionaldocs/connections.md
additionaldocs/development.md
additionaldocs/getting-started/README.md
packages/graph-explorer-proxy-server/node-server.js

Updated the documentation to better describe the docker setup and reformatted other parts of the documentation to improve readability.
Also, fixed the log message when the Express server starts.
- Read through the documentation changes.
- Verify the steps in the documentation work as intended
- Run the proxy server to see the updated log message
- Addresses #405
- Addresses #407
- Addresses #402 
license.

Docker setup documentation

---

packages/graph-explorer/jest.config.ts
packages/graph-explorer/src/components/Graph/hooks/useRenderBadges.ts
packages/graph-explorer/src/components/utils/canvas/drawImage.ts
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/openCypher/openCypherExplorer.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/core/ConfigurationProvider/fetchConfiguration.ts
packages/graph-explorer/src/core/ConfigurationProvider/isConfiguration.ts
packages/graph-explorer/src/core/StateProvider/StateProvider.tsx
packages/graph-explorer/src/core/connector.ts
packages/graph-explorer/src/hooks/useEntities.test.ts
packages/graph-explorer/src/hooks/useNeighborsOptions.test.ts
packages/graph-explorer/src/hooks/useTextTransform.test.ts
packages/graph-explorer/src/modules/EntitiesFilter/useFiltersConfig.test.ts
packages/graph-explorer/src/modules/KeywordSearch/toAdvancedList.ts
packages/graph-explorer/src/utils/env.ts
packages/graph-explorer/src/utils/index.ts
packages/graph-explorer/src/utils/testing/setupTests.ts

I kept getting errors about the `import.meta.env.DEV` calls in our code. The common fix was to mock the code using that data. But a better approach is to mock the data itself.
Since this is needed globally, I've configured a global setup test file for mocks used everywhere. We can always opt out or override any of these mocked types if needed for specific tests.
I've also added the `localforage` mock since we always want that mocked when we are testing React state logic.
- Run the tests
license.

Automatic setup of some common mocks

---

.vscode/launch.json
Changelog.md
packages/graph-explorer/src/components/Graph/hooks/useRenderBadges.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/hooks/useEntities.ts
packages/graph-explorer/src/hooks/useExpandNode.ts
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/useNodeBadges.ts

This is a collection of minor changes that I made along the way to deferred neighbor counts.
- Add a test for one of the common keyword search template cases
- Make "no results" toast message consistent across expand neighbor requests
- Consolidate mutltiple `useEntities()` hook call in `GraphViewer`
- Fix VSCode Jest debugging
- Fix edge case where node badges can be stale if the canvas hasn't been resized
- Run tests
- Sanity check UI
- #339 
- #341 
license.

Minor changes

---

packages/graph-explorer/src/core/ConfigurationProvider/useConfiguration.ts
packages/graph-explorer/src/hooks/useEntities.ts

I discovered that `setEntities` was being recreated every time it was called because I needed to call it in a `useEffect`, which meant it needed to be in the dependency array. This led to an infinite loop that locks up the browser.
The main cause was the config value, which changes when the schema changes, which is changed when adding nodes and edges.
However, the config is in Recoil state. So I get the config value from Recoil snapshot instead of the hook. I also use the setter provided in the `useRecoilCallback` utility.
- Add nodes to graph
- Expand nodes
- #341 
- #339 
license.

Ensure setEntities is not recreated on each render

---

Changelog.md
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.styles.ts
packages/graph-explorer/src/modules/common/NeighborsList/NeighborsList.styles.ts
packages/graph-explorer/src/modules/common/NeighborsList/NeighborsList.tsx

The expand sidebar scrolling is annoying to use when vertical height is limited. It was using percentage heights for sections of the UI.
Instead, I allow the full content beneath the vertex header to be scrolled. The expand button will be in the bottom corner if there is enough height to accomplish that without scrolling. If not, the user will need to scroll for the expand button.
When there are more than 5 neighbors, A "show more" button will appear. When clicked, all the neighbors will show. The user can collapse it again.
Here is a 30 second video showing off this new behavior.
https://github.com/aws/graph-explorer/assets/212862/da47da08-e0fc-48df-9e45-3ef3e98b52ee
license.

Fix expand sidebar scrolling

---

packages/graph-explorer/.eslintrc.json
packages/graph-explorer/package.json
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/core/ConnectedProvider/ConnectedProvider.tsx
packages/graph-explorer/src/hooks/useUpdateVertexTypeCounts.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearchQuery.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx
pnpm-lock.yaml

- Adds ESLint plugin for React Query
- Adds React Query dev tools (disabled for production)
- Fixes new lint issues
- Removes unnecessary `useMemo` for query key (automatically memoized)
- Moves retry and 1 minute cache to global React Query defaults (can be overridden per query if needed)
- Add `explorer` to query key so connections are unique queries
- Tested in development mode locally
- Tested in built Docker container from local code to see production behavior
- Related to #304 
license.

React query ESLint and dev tools

---

packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/hooks/useUpdateVertexTypeCounts.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

- Moves the node count by type query in to the shared queries file
- Adds container component to ensure `vertexType` is assigned (which it always will be)
- Tested by trying Data Explorer on a few different connections
- Observed React Query dev tools
- Resolved #337
license.

Move node count by type query

---

Changelog.md
packages/graph-explorer/src/components/AdvancedList/AdvancedList.styles.tsx
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.styles.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx

- Add vertical padding to list item content
- Allow flex items to take full width in connection detail pane
- Move existing config deconstruction logic in to `CreateConnection` modal code
- Rename form properties to match config connection property names
- Remove unnecessary mapping after rename
- Add separate boolean for fetch timeout enabled
- This fixes an issue where if the user deletes all text in the input, the check box automatically unchecks and the input disappears
- Verified old config values carry over properly
- Verified new and old connections are created/updated properly
- Resolves #292
license.

Create connection cleanup

---

Changelog.md
README.md
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/testUtils/globalMockFetch.ts
packages/graph-explorer/src/core/ConfigurationProvider/types.ts
packages/graph-explorer/src/core/connector.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/index.tsx
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx
packages/graph-explorer/src/utils/constants.ts

Adds a global node expansion limit to the connection.
- Default is off for new and existing connections
- Updated documentation for new environment value `GRAPH_EXP_NODE_EXPANSION_LIMIT`
- Ensure fetch neighbors and neighbor counts queries respect the limit
- Updated tests
- Tested limits respected across query engines
- Tested queries are refetched when limit changes
- Tested new and existing connections function as expected
- Resolves #442 
license.

Add expand limit to connection

---

THIRD_PARTY_LICENSES.txt
packages/graph-explorer/package.json
packages/graph-explorer/src/connector/sparql/queries/fetchBlankNodeNeighbors.ts
packages/graph-explorer/src/connector/sparql/queries/fetchNeighborsCount.ts
packages/graph-explorer/src/connector/sparql/templates/classWithCountsTemplates.ts
packages/graph-explorer/src/connector/sparql/templates/classesWithCountsTemplates.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/neighborsCount/blankNodeNeighborsCountTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/neighborsCount/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighbors/blankNodeOneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighbors/oneHopNeighborsBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighbors/oneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/predicatesByClassTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/predicatesWithCountsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/subjectPredicatesTemplate.ts
pnpm-lock.yaml

Minor cleanup that doesn't change any critical logic.
- Adds `dedent` dependency which will remove indentation from strings
- Use dedent on SPARQL queries
- Convert closure expressions to functions
- Did a brief smoke test
- #384 
- #344
license.

Sparql template cleanup

---

Changelog.md
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.ts
packages/graph-explorer/src/hooks/useEntities.test.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/utils/testing/normalize.ts

Fixes openCypher issues around neighbor expansion and neighbor counts.
- Fixes issue where neighbor query returned edges with the wrong type for source and target types
- Fixes neighbor count to respect limits
- Fixes limit and offset in neighbor query
- Fixes edges in neighbor query to return all edges between source and target nodes
- Fixes limit and offset calculations in expand side bar to use typed counts rather than total counts
- Better formatting of queries in logic and tests
- Tested many expansion options
- Tested multiple expansions with limit (paging results)
- Tested with bidirectional edges
- Resolves #389 
- Resolves #343 
license.

Fix openCypher neighbor expansion and counts

---

Changelog.md
packages/graph-explorer/src/components/Graph/hooks/useAddClickEvents.ts

When double clicking a node it would not always register as a double click. I've updated the time delay for double clicks to be 300 ms and updated the algorithm to be more reliable.
- Verified double clicking is much more reliable
license.

Fix double click behavior

---

Changelog.md
packages/graph-explorer/src/components/LoadingSpinner/LoadingSpinner.tsx
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/hooks/useUpdateNodeCounts.ts
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/modules/common/NeighborsList/NeighborsList.tsx

- Updates label of the "Show More" toggle button in the neighbors list
- Better handling of props in the `LoadingSpinner` component
- Move to new file and rename `useUpdateNodeCounts()`
- Add new related hook that focuses on a single node `useUpdateNodeCountsQuery()`
- Use the hook to get progress and error info about the node counts query
- Resolves #438
license.

Expand cleanup & progress UI

---

Changelog.md
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx

When the user double clicks a node GE will now expand the next 10 nodes.
Before it would check if the neighbors count is greater than 10. If it is, then show the expand sidebar. If not, it expands.
Now it will always expand, but at most 10 items.
- Verified with all three query engines
- SPARQL still needs work on the query side, but that is happening in a different branch
- Resolves #318 
- Resolves #460 
license.

Expand the next 10 neighbors

---

Changelog.md
packages/graph-explorer/src/components/Carousel/Carousel.tsx

In the search modal when the user selects a search result you would see a error in the browser's console.
This was caused by the use of `setTimeout()` within a `useEffect()`. This is almost never a good idea.
I have replaced it with `useTransition()`, which is the React supported way of delaying a task until the next render.
- Verified no more error
- Verified multiple selection still works
- Verified swiping still works
- Verified prev/next buttons work
**The original error**
- Fixes #435 
license.

Fix swiper error

---

Changelog.md
packages/graph-explorer-proxy-server/node-server.ts
packages/graph-explorer-proxy-server/package.json
pnpm-lock.yaml

- Add `body-parser` types package
- Increase body-parser limit to 50mb
- Resolves #484 
- Resolves #410
license.

Increase request body size limit for proxy server

---

Changelog.md
packages/graph-explorer/src/connector/openCypher/queries/keywordSearch.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts

The openCypher version of the keyword search query would execute multiple parallel requests if the user has chosen "All" for the "Node Type" field, which is the default option.
Instead, we use a single query that contains all the node labels in the WHERE clause. Here's an example from the Airports database.
```
MATCH (v)
WHERE (v:`airport` OR v:`continent` OR v:`country` OR v:`version`)
RETURN v AS object
ORDER BY id(v)
LIMIT 10
```
I've also updated the query generation to better handle any of the search parameters that can be passed.
- Add ability to handle multiple vertex types in a single request
- Fix limit and offset query handling
- Sort by ID for consistency
- Better formatting of query strings
- Improved testing
- Test search with different parameters
- Partially addresses #481 …

OpenCypher singular search query

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchSchema.ts
packages/graph-explorer/src/connector/gremlin/templates/edgesSchemaTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/edgesSchemaTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/verticesSchemaTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/verticesSchemaTemplate.ts
packages/graph-explorer/src/connector/testUtils/globalMockFetch.ts
packages/graph-explorer/src/setupTests.ts
packages/graph-explorer/src/utils/index.ts
packages/graph-explorer/src/utils/logger.ts

- Improve vertex schema template query by using union
- Improved formatting for edge schema template (no query changes)
- Move the summary API request in to a function
- Add logger util, which is a thin wrapper around `console.log()` for now
- Add debug logging around schema fetching for Gremlin Explorer
- Fix global mock for `./utils/env`
```gremlin
g.V()
.project("airport", "country")
.by(V().hasLabel("airport").limit(1))
.by(V().hasLabel("country").limit(1))
.limit(1);
```
```gremlin
g.V().union(
__.hasLabel("airport").limit(1),
__.hasLabel("country").limit(1)
)
.fold()
.project("airport", "country")
.by(unfold().hasLabel("airport"))
.by(unfold().hasLabel("country"))
```
- Tested on small database
- Tested on large database (schema sync in roughly 1 second)
- Resolves #483 
- Resolves …

Improve Gremlin schema sync performance

---

Changelog.md
packages/graph-explorer/src/connector/openCypher/queries/fetchSchema.test.ts
packages/graph-explorer/src/connector/openCypher/queries/fetchSchema.ts
packages/graph-explorer/src/connector/openCypher/templates/edgeSchemaTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/edgesSchemaTemplate.ts
packages/graph-explorer/src/connector/sparql/queries/fetchSchema.ts
packages/graph-explorer/src/utils/batchPromisesSerially.ts
packages/graph-explorer/src/utils/constants.ts
packages/graph-explorer/src/utils/index.ts
pnpm-lock.yaml

In a few cases we can not avoid sending many parallel requests to the server. Since some servers implement throttling, we want to batch up those requests in to smaller groups and execute them in serial.
- Update openCypher keyword search query template
- Fix limit and offset
- Add ability to handle multiple vertex types in a single request
- Sort by ID
- Better formatting of strings
- Consolidate multiple openCypher search requests in to a single request
- Add `batchPromisesSerially()` function to manage the batching logic
- Batch all the `Promise.all()` occurrences in the code
- Default concurrent request batch size is set to 10
- Tested openCypher search
- Tested openCypher schema sync
- Tested sparql schema sync
- Resolves #481 
- Related to PR #493 
license.

Batch concurrent requests serially

---

Changelog.md
packages/graph-explorer/src/hooks/useNeighborsOptions.ts
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandFilters.tsx

Before this change, Goal would be the selected neighbor type for expansion. But it is already fully expanded.
Now, we select Team instead because it is the first neighbor type with collapsed neighbors.
license.

Fix expand selected type

---

Changelog.md
packages/graph-explorer-proxy-server/node-server.ts
packages/graph-explorer/src/connector/LoggerConnector.ts
packages/graph-explorer/src/connector/fetchDatabaseRequest.ts
packages/graph-explorer/src/core/connector.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/hooks/useSchemaSync.ts
packages/graph-explorer/src/utils/createDisplayError.test.ts
packages/graph-explorer/src/utils/createDisplayError.ts

Modify the way logging is sent to the proxy server.
- Ensure we only send logs to the server when using the proxy server
- Use `ClientLoggerConnector` so we don't have to deal with null
- Change `/logger` endpoint to be a POST instead of GET
- Enable server logging for both DEV and PROD (in DEV it will just be logged to the terminal)
- Add check for `isNeptuneError()` that will use the message from the Neptune error in the `throw new Error()` message
- Add logging for errors in node expansion
- Add display error for malformed queries
- Use display error for node expansion error notification
- Tested by modifying the expand neighbor query template to fail
license.

Server logging

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/testUtils/globalMockFetch.ts

Order by vertex was added in Gremlin v3.6.0. In order to at least partially support older versions I've updated the query to use `.order().by(id())` instead.
- Tested with Neptune v1.2.0.1
- Tested with Neptune v1.3.2.1
license.

Update Gremlin query to avoid order by vertex

---

packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandFilters.tsx

I noticed a small bug in the search loading screen where the text was missing some spaces.
I also was reading about [how to avoid `useEffect()`](https://react.dev/learn/you-might-not-need-an-effect#resetting-all-state-when-a-prop-changes) and implemented two of those patterns in parts of code that reset state based on other state changes.
- Tested search loading
- Tested node expansion side bar filters
license.

Spacing fix and remove a couple `useEffect` uses

---

packages/graph-explorer/src/core/ConfigurationProvider/types.ts
packages/graph-explorer/src/core/ConfigurationProvider/useConfiguration.ts
packages/graph-explorer/src/hooks/useEntitiesCounts.test.ts
packages/graph-explorer/src/hooks/useEntitiesCounts.ts
packages/graph-explorer/src/hooks/useNeighborsOptions.test.ts
packages/graph-explorer/src/hooks/useTextTransform.test.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionData.tsx
packages/graph-explorer/src/modules/EdgesStyling/SingleEdgeStyling.tsx
packages/graph-explorer/src/modules/EntitiesFilter/useFiltersConfig.tsx
packages/graph-explorer/src/modules/EntityDetails/EdgeDetail.tsx
packages/graph-explorer/src/modules/EntityDetails/NodeDetail.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/useGraphStyles.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.test.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.ts
packages/graph-explorer/src/modules/NodeExpand/NodeExpandFilters.tsx
packages/graph-explorer/src/modules/NodesStyling/SingleNodeStyling.tsx
packages/graph-explorer/src/modules/common/VertexHeader.tsx
packages/graph-explorer/src/utils/testing/randomData.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

Adds a clean hook around getting the vertex type config for a given vertex, array of vertices, or all vertices.
This is step one in cleaning up the config/schema access code and make it more "React" like.
- Smoke test
license.

Refactor vertex type config hook

---

Changelog.md
process-environment.sh

I noticed that when running Graph Explorer in Neptune Notebook it would sometimes fail to get the default connections. I determined it is because every time the Notebook is rebooted another entry is added to the `defaultConnection.json` file. But it is missing a comma between them so it is invalid JSON and can't be parsed by the JavaScript code.
So instead, each startup will replace the existing `defaultConnection.json` file with the current environment values. This will ensure that only one connection is present in the file.
- Tested in local docker environment with Neptune Notebook like settings
license.

Replace existing defaultConnection file on startup

---

Changelog.md
additionaldocs/sagemaker/graph-explorer-neptune-analytics-policy.json
additionaldocs/sagemaker/graph-explorer-neptune-db-policy.json
additionaldocs/sagemaker/install-graph-explorer-lc.sh

Updates the SageMaker example script.
- Adds CloudWatch logging to Docker container run command
- Updates logging text to use product name `Graph Explorer`
- Adds instructional comments to parts of script that the user must change manually
- Removes parameter parsing, since version is not passed via script parameter in this case
- Adds graph-notebook installation to better reflect full production Lifecycle used in Neptune Notebooks
license.

SageMaker example script update

---

packages/graph-explorer-proxy-server/logging.ts

I accidentally left a `pino-http` import in the code, which was supposed to be removed. This broke the build.
I'm fixing the build in this PR. My next PR will be to enable TypeScript and ESLint on the server code, which should catch stuff like this in the future.
license.

Fix build pipeline

---

Changelog.md
eslint.config.mjs
package.json
packages/graph-explorer-proxy-server/node-server.ts
pnpm-lock.yaml

Adds linting to the server code
- Updates `eslint-plugin-react` for flat file configs
- Removes ignore entry for server code
- Fix lint errors in `node-server.ts`
- Add server code to `pnpm check:types`
license.

Server linting

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
pnpm-lock.yaml

I noticed there was a clean step in `/packages/graph-explorer/package.json` and it used `rimraf`, but `rimraf` wasn't installed in the devDepencies. So I've added it to both the client and server, with the accompanying node scripts.
- Run `pnpm clean` at the root to delete the `*/dist` folders
license.

Add clean steps using rimraf

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts

We put the `queryId` in the headers for Gremlin and SPARQL requests so they can be cancelled by the proxy server. But some database endpoints will report CORS issues if the header contains unexpected values.
If we are not using the proxy server then there is no reason to have the `queryId` in the headers.
- Tested against Neptune
- Tested against `https://id.nlm.nih.gov/mesh` (SPARQL)
- Resolves #530 
license.

Only send queryId when using proxy server

---

Changelog.md
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts

The order by clause was causing the default initial search query in openCypher to be extremely slow. Removing it makes the order less predictable, but is preferable to the slow query.
We will need to figure this out if we ever want to have paginated search results:
- #106 
- Tested in very large data set on Neptune
- Resolves #531 
license.

Remove order by in cypher search query

---

packages/graph-explorer/src/core/StateProvider/userPreferences.ts
packages/graph-explorer/src/hooks/usePrevious.test.ts
packages/graph-explorer/src/hooks/usePrevious.ts
packages/graph-explorer/src/modules/EdgesStyling/SingleEdgeStyling.tsx
packages/graph-explorer/src/modules/NodesStyling/SingleNodeStyling.tsx

This fixes a gnarly performance issue when the number of node or edge types is large (roughly over 20). The browser would essentially lock up and be nearly unuseable.
The problem was that the effect that watch for the `Input` value change was being fired way too often, including the initial render, and the state update is very slow.
The fix was to properly debounce the value change and also compare to previous value. This led to another fix in the `usePrevious` hook where it didn't always have the correct value.
And finally, I did some cleanup in the `SingleEdgeStyling` and `SingleNodeStyling ` components to lean on Recoil selectors to simplify the logic.
I accidentally pushed the changelog update to `main` directly. Since it is a non-destructive change, I'm just going to leave it there …

Fix styling sidebar performance

---

Changelog.md
packages/graph-explorer/src/hooks/usePrefixesUpdater.ts
packages/graph-explorer/src/utils/generatePrefixes.test.ts
packages/graph-explorer/src/utils/generatePrefixes.ts
packages/graph-explorer/src/utils/logger.ts

This fixes an issue with RDF data sets that contain upper case characters in the URI. For example:
```
http://www.ExampleData.com/Entity
```
These uppercase characters would cause the prefix generator to miss the existing entry in the prefixes array, causing a new entry to be created. That new entry would be converted to lower case. On the next pass the same thing would happen looped to infinity.
This infinite loop would cause Graph Explorer to crash.
To fix, I made the search for an existing entry be case insensitive.
- Tested with dataset that produces the crash
- Added unit tests for case sensitivity
- Resolves #545
license.

Fix prefix updater

---

Changelog.md
packages/graph-explorer/src/components/Button/Button.styles.ts
packages/graph-explorer/src/components/NotInProduction.tsx
packages/graph-explorer/src/components/Tabular/controls/ExportControl/ExternalExportControl.tsx
packages/graph-explorer/src/components/Typography.tsx
packages/graph-explorer/src/components/index.ts
packages/graph-explorer/src/core/AppLoadingPage.tsx
packages/graph-explorer/src/core/StateProvider/StateDebug.tsx
packages/graph-explorer/src/core/StateProvider/StateProvider.tsx
packages/graph-explorer/src/core/StateProvider/schema.ts
packages/graph-explorer/src/modules/AvailableConnections/AvailableConnections.tsx
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx
packages/graph-explorer/src/utils/fileData.ts
packages/graph-explorer/src/utils/saveConfigurationToFile.ts
packages/graph-explorer/tailwind.config.ts

Added some debug actions to the active connection. These will be hidden when the app is run in production mode using the new `NotInProduction` component.
There are some other small changes made as well.
These actions are useful when testing schema synchronization issues. There's a lot of complicated logic around states that are difficult to set up. These actions make it easier to set up those scenarios
- Delete Schema - deletes the schema entry in storage for the active connection
- Reset Last Updated - sets the `lastUpdate` timestamp on the schema to `undefined`
- Last Sync Failed - sets the flag that indicates a failure on the last schema sync
- Reset Vertex Totals - sets all vertex type totals to `undefined`
- Change button style to have a slightly bolder font
- Remove unnecessary …

Add debug actions

---

Changelog.md
additionaldocs/sagemaker/install-graph-explorer-lc.sh

- Added handling and fallback for possible failure of `awslogs` driver on Docker container startup, in the absence of required IAM permissions for CloudWatch logging.
license.

Add SageMaker script fallback for CloudWatch logging driver failure

---

Changelog.md
package.json
packages/graph-explorer/package.json
packages/graph-explorer/vite.config.ts

Vite is the tool we use for fast development on the React client side. It has a feature to run as a server, but it is discouraged to use in production.
We require running the client side through the proxy server. But there was an option in the code to run the client by itself without the proxy server.
This PR removes those options.
- Remove certificate handling in Vite config (still exists on the proxy server)
- Remove PNPM script to launch Vite server
- Smoke test
- None
license.

Remove Vite production server

---

packages/graph-explorer/src/core/StateProvider/edges.test.ts
packages/graph-explorer/src/core/StateProvider/edges.ts
packages/graph-explorer/src/core/StateProvider/entitiesSelector.ts
packages/graph-explorer/src/core/StateProvider/nodes.test.ts
packages/graph-explorer/src/core/StateProvider/nodes.ts
packages/graph-explorer/src/core/StateProvider/schema.test.ts
packages/graph-explorer/src/core/StateProvider/schema.ts

The process that updates the schema when new nodes and edges are added to the graph had an issue. The schema would be updated from the `nodeSelector` then the `edgeSelector` from within the `entitySelector`. But that state doesn't merge the two updates properly.
To solve this I pulled the logic out of the node and edge selectors and placed it in the entity selector. This will only update the schema once during the `setEntities()` call.
I also rewrote the schema merging logic and added a bunch of tests around it.
- Added tests
- Verified using Airports DB where the `contains` edge is not present after a schema sync, and is added when expanding an Airport to its connected country.
- Resolves #568 
license.

Fix updating schema from expansion

---

package.json
packages/graph-explorer/src/core/StateProvider/schema.ts
packages/graph-explorer/src/hooks/useSchemaSync.ts
packages/graph-explorer/src/hooks/useUpdateSchema.test.ts
packages/graph-explorer/src/hooks/useUpdateSchema.ts
packages/graph-explorer/src/hooks/useUpdateVertexTypeCounts.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionData.tsx
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx
packages/graph-explorer/src/utils/testing/index.ts
packages/graph-explorer/src/utils/testing/randomSchemaResponse.ts

This fixes the issue where a schema sync failure would break a previous good schema sync.
- Fix issue checking for null vs default value in recoil setter
- Make each schema update scenario a separate function
- Add tests for each scenario
- Add new debug action to reset all schema counts
- Use reset for debug action to delete existing schema
- Remove `--verbose` on `pnpm check:types` because it was too much noise
- Remove some unnecessary curly braces around string props
- Verified using Neptune connection with and without SSH tunnel to provoke schema sync failure
- Verified using debug actions to manipulate schema data
- Resolves #569 
license.

Fix scenario where sync fails

---

Changelog.md
packages/graph-explorer-proxy-server/src/env.ts
packages/graph-explorer-proxy-server/src/logging.ts
packages/graph-explorer-proxy-server/src/node-server.ts
packages/graph-explorer/src/connector/LoggerConnector.ts
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/openCypher/openCypherExplorer.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/core/connector.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/hooks/useSchemaSync.ts

Sends DB query to server to log. Also sends broad context at the explorer request level to the server.
- Add DB query string logging to proxy server at `debug` level
- Logs client side explorer requests to server at `info` level
- Adds explorer request logs to all client side explorers (openCypher and SPARQL)
- Fix bug in remote logger creation, where the remote logger would never be created
- Send logs to both client and server when using remote logger
- Rename `logger` to `remoteLogger` to be more clear when it is being used
- Don't log in the request middleware for path `/logger` to reduce noise
Reworked how environment values are parsed. 
- Move access to `process.env` to a single place in `env.ts`
- Add Zod schema for environment values the server cares about
- Default values are …

Log DB query & environment values

---

Changelog.md
packages/graph-explorer-proxy-server/src/env.ts
packages/graph-explorer-proxy-server/src/logging.ts
packages/graph-explorer-proxy-server/src/node-server.ts
packages/graph-explorer/src/connector/fetchDatabaseRequest.ts
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/openCypher/openCypherExplorer.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/core/StateProvider/configuration.test.ts
packages/graph-explorer/src/core/StateProvider/configuration.ts
packages/graph-explorer/src/core/StateProvider/userPreferences.ts
packages/graph-explorer/src/core/connector.ts
packages/graph-explorer/src/core/featureFlags.ts
packages/graph-explorer/src/utils/testing/randomData.ts
packages/graph-explorer/src/workspaces/Settings/SettingsGeneral.tsx

Adds a new setting for enabling or disabling logging of the database queries for Graph Explorer operations.
- Default value is disabled
- Applies to all queries across all connections that use the proxy server
- Setting is communicated to the server through a new HTTP header `db-query-logging-enabled`
- If the setting is missing it is assumed disabled
I went down some alternative paths that contained some cleanup of existing code. I'm including those here, but can break them out to a separate PR if desired.
- Don't log requests for CORS `OPTIONS` method to reduce logger noise
- Updated random data functions for tests so that when generating `undefined` values the properties won't be on the resulting object
- In JavaScript `prop: undefined` is treated differently than an "undefined" prop …

Setting to enable or disable DB query logging

---

packages/graph-explorer/index.html
packages/graph-explorer/src/core/AppErrorPage.tsx
packages/graph-explorer/src/utils/constants.ts
packages/graph-explorer/src/workspaces/Settings/LoadConfigButton.tsx

The 404 happens because the `BASE_URL` environment value does not have a terminating `/`. So the URL was:
```
/proxy/9250/explorer
```
This leads to a redirect that leads to a 404.
The URL should be
```
/proxy/9250/explorer/
```
So I added a constant that is used for the two reload buttons. It checks whether the `BASE_URL` has an ending `/` before adding one.
I also updated updated the `index.html` to use `BASE_URL` hoping this would help with the CORS issue. It did not. But I'd like to keep the change since it removes a need for passing our custom `GRAPH_EXP_ENV_ROOT_FOLDER` environment value through the VITE config.
- Tested in local environment
- Tested in Neptune Notebook environment
- Resolves #579 
license.

Fix 404 issue on reload

---

additionaldocs/sagemaker/install-graph-explorer-lc.sh

Uses a parameter to the cloudwatch log driver to parse the logs for multiline entries.
One side effect is that anything that doesn't use the standard log format will be rolled up in to a single entry.
But I quite like this. The only occurrences should be some startup and shutdown messages that don't go through the logger. Rolling these up is convenient.
SPARQL query rolled up
- Resolves #583 
license.

Add multiline log pattern

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/queries/fetchSchema.ts

Batches up Gremlin queries that gather sample nodes and edges to know the properties.
- Batch size 100 node & edge types
- **NOTE FOR REVIEWER:** If you switch the diff style to ignore whitespace you'll see not much has changed, just the `for` loop added.
- Tested on a database with over 1,800 edge types and over 3,000 node types
- Resolves #592 
- Resolves #593
license.

Batch queries gathering sample node & edges

---

packages/graph-explorer/src/connector/gremlin/queries/keywordSearch.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearchQuery.ts

The search query parameter `searchById` may have done something in the past, but ever since we added the ability to search specifically by the ID field it has served no purpose. But I've been too cautious to remove it before because I wasn't confident enough in how the search algorithm worked.
Now I am confident enough to remove it. It does not affect the logic whatsoever. There are two places where the search query is executed:
- In keyword search, where the value is always set to `true`
- In data explorer, where a search term is never passed
So, in reality, the value is always `true` or it is irrelevant. Removing it simplifies the search logic and clarifies intent in the algorithm.
- Ran through search permutations using all forms of search parameters with and without search terms in …

Remove searchById

---

Changelog.md
packages/graph-explorer/src/components/IconButton/IconButton.tsx
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.styles.ts
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.tsx

Fixes the alignment of the close button in the search panel to be centered in the row of inputs.
license.

Fix keyword search close button alignment

---

Changelog.md
packages/graph-explorer-proxy-server/src/error-handler.ts
packages/graph-explorer-proxy-server/src/logging.ts
packages/graph-explorer-proxy-server/src/node-server.ts
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchSchema.test.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchSchema.ts
packages/graph-explorer/src/connector/openCypher/openCypherExplorer.ts
packages/graph-explorer/src/connector/openCypher/queries/fetchSchema.test.ts
packages/graph-explorer/src/connector/openCypher/queries/fetchSchema.ts
packages/graph-explorer/src/connector/sparql/queries/fetchSchema.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts

- Log out requests with status 300 - 400
- Format request log statements better
- Use response "finish" event to capture request log which is more consistent
- Call `JSON.parse()` with remote logger since it uses `JSON.stringify()` on the client end
- Removes the extra double quotes in the log statements
- Send schema sync log messages to the server
- Add schema sync log messages to openCypher (already existed on Gremlin and SPARQL)
- Add summary log messages with counts after schema sync
- Tested request error handling by sending bad query
- Tested schema sync with each query language
- Resolves #605
license.

Improve logging

---

.dockerignore
.github/workflows/build_docker.yml
Changelog.md

- Removes `package` write permissions from Docker image workflow
- Updates `.dockerignore` file to exclude development files and documentation
license.

Remove development and documentation related files from Docker image

---

Dockerfile

Updated the Dockerfile to use the latest Node version added in #614.
Verified via manual ECR deployment test.
license.

Update Dockerfile to latest Node version

---

Changelog.md
Dockerfile
package.json
packages/graph-explorer/package.json
pnpm-lock.yaml

The main goal of this change was to reduce or eliminate security vulnerabilities in the Docker image.
- Update base image to use `amazonlinux:2023`
- Move `vite-tsconfig-paths` to devDependencies where it should be
- Update `Dockerfile` to cleanup any devDepencies
- This required first removing the `node_modules` folders for all packages in the monorepo, then reinstall only the production dependencies, skipping scripts since husky is no longer installed and would fail
- Local docker build and run to ensure functionality
- Checked vulnerabilities in Docker image
license.

Use Amazon Linux 2023 & production dependencies only

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.test.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchTemplate.test.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.ts

When searching across all vertex types, the query that is generated will include a list of all the known vertex types. This filter is unnecessary and can lead to slower query performance.
Once the filter is removed we must consider a result from the query that include nodes which have no type or label.
- Gremlin does not support vertices without labels, so is not a concern
- OpenCypher supports empty labels, but Neptune doesn't support them
- Originally, I added a filter to ensure at least one label exists, but this was noticeably slow so I removed it
- If the label array is empty we'll use an empty string for the label to ensure the rest of the app continues to function properly
- SPARQL allows resources without classes, but the query already filters down to only the resources with a …

Remove filter for all vertex types

---

packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/testUtils/globalMockFetch.ts

The keyword search query template functions had a default value for the limit. Since the two places it is called already pass the limit (search and data explorer) I have removed the parameter default to allow for an unbounded request if desired.
- Tested with all query languages
- Resolves #622 
license.

Remove limit defaults for search query

---

Changelog.md
packages/graph-explorer/src/connector/sparql/queries/fetchSchema.ts
packages/graph-explorer/src/core/StateProvider/configuration.test.ts
packages/graph-explorer/src/core/StateProvider/configuration.ts
packages/graph-explorer/src/hooks/useDisplayNames.ts
packages/graph-explorer/src/modules/EntityDetails/NodeDetail.tsx
packages/graph-explorer/src/modules/NodesStyling/SingleNodeStyling.tsx
packages/graph-explorer/src/utils/constants.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

If a node has a property named `id` then Graph Explorer would not allow switching the display name and description for the node style. This is because the actual node ID used the key `id` which conflicts with the user property `id`.
To fix it I switched the id key to use `~id`, which is the standard in other AWS tooling.
- Tested schema sync
- Tested node styling by changing display name and display description
- Resolves #618
license.

Fix clashing node ID property

---

Changelog.md
packages/graph-explorer/src/components/Button/Button.styles.ts
packages/graph-explorer/src/components/IconButton/IconButton.styles.ts
packages/graph-explorer/src/components/ModuleContainer/components/ModuleContainerHeader.tsx
packages/graph-explorer/src/components/ModuleContainer/components/ModuleContainerHeaderActions.styles.ts
packages/graph-explorer/src/components/TextArea/TextArea.styles.ts

Fix issue with style where the focus shadow would remain on buttons after clicking. Using `focus-visible` instead of `focus` will only apply the style when the user is using the keyboard or other accessibility tool to navigate the website. When the user uses a mouse/trackpad, the `focus-visible` styles will not be applied.
- Verified `Select` and `Input` still show correct focus styles
- Verified tab to focus shows focus shadow
- Verified `Button` and `IconButton` no longer leave the focus shadow on click
- Fixes #273
license.

Use focus-visible instead of focus

---

packages/graph-explorer/src/@types/entities.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/connector/sparql/mappers/mapIncomingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapOutgoingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapRawResultToVertex.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/hooks/useUpdateNodeCounts.ts
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/utils/branded.ts
packages/graph-explorer/src/utils/index.ts
packages/graph-explorer/src/utils/testing/randomData.ts

Using a [branded type](https://egghead.io/blog/using-branded-types-in-typescript) for the `VertexId` and `EdgeId` values allows me to enforce that a specific ID type is being passed in to the functions.
Also, fixes a bug where the ID type was not being passed to the neighbor count query. This only affects a small optimization in the query when the ID type is a number instead of a string. So the bug did not result in any kind of error.
- Verified no change to behavior
license.

Use strong types for VertexId and EdgeId

---

packages/graph-explorer/src/@types/entities.ts
packages/graph-explorer/src/@types/react-table-config.d.ts
packages/graph-explorer/src/components/Tabular/Tabular.tsx
packages/graph-explorer/src/components/Tabular/TabularControlsProvider.tsx
packages/graph-explorer/src/components/Tabular/controls/ColumnSettingsControl/ColumnItem.tsx
packages/graph-explorer/src/components/Tabular/controls/ExportControl/getNestedObjectValue.ts
packages/graph-explorer/src/components/Tabular/controls/ExportControl/transfomerToCsv.ts
packages/graph-explorer/src/components/Tabular/helpers/tableInstanceToTabularInstance.ts

The `Vertex` and `Edge` types have a type definition that allowed adding additional properties at runtime. Since TypeScript does not actually do any typing at runtime, this is unnecessary.
This extra type information was used by the abstraction around React Table. This essentially undoes a part of a change I made months ago to fix the table export.
- #297
- Verified table still works as it did before
- Verified table export still works as it did before (including trying all the export options)
license.

Remove need for extendable type definition for Vertex and Edge

---

packages/graph-explorer/src/@types/entities.ts
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapResults.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighbors.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchSchema.ts
packages/graph-explorer/src/connector/gremlin/queries/keywordSearch.ts
packages/graph-explorer/src/connector/gremlin/types.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.test.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/openCypher/queries/fetchNeighbors.ts
packages/graph-explorer/src/connector/openCypher/queries/keywordSearch.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/connector/sparql/mappers/mapIncomingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapOutgoingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapRawResultToVertex.ts
packages/graph-explorer/src/connector/sparql/queries/fetchNeighbors.ts
packages/graph-explorer/src/connector/sparql/queries/keywordSearch.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/hooks/useDisplayNames.ts
packages/graph-explorer/src/hooks/useEntities.test.tsx
packages/graph-explorer/src/utils/testing/randomData.ts

This logic is from my prototype work with the raw query editor. I had to support many more types of Gremlin responses, so I expanded the mapping logic.
- Added `entityType: 'vertex' | 'edge'` to both Vertex and Edge types to aid in discriminated unions
- Added `__isFragment` to Vertex and Edge to flag when a query returns a vertex or edge without any properties (this will allow us query for the details later)
- Added recursive mapping logic for Gremlin results that will properly map nearly any data type within the query result
- Validated all three query languages
- None (code improvement)
license.

Entity mapping

---

packages/graph-explorer/src/core/StateProvider/userPreferences.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx
packages/graph-explorer/src/modules/GraphViewer/internalComponents/ContextMenu.tsx
packages/graph-explorer/src/modules/SearchSidebar/NodeSearchResult.tsx
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx

New users should see the search sidebar open by default when they launch for the first time.
- Adjusted add and remove buttons for search results
- Use primary button colors for both add and remove
- Change remove icon to circle with minus
- Add tooltip
- Made search sidebar open by default for new users
- Add padding to empty states in connection screen
- Verified locally by deleting my local graph explorer database to simulate a new user
- Related to #665 
license.

Open search by default

---

Changelog.md
packages/graph-explorer/src/modules/AvailableConnections/AvailableConnections.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/internalComponents/ContextMenu.styles.ts
packages/graph-explorer/src/modules/GraphViewer/internalComponents/ContextMenu.tsx
packages/graph-explorer/src/modules/SearchSidebar/NodeSearchResult.tsx

- Update the icon for the remove node button in the context menu
- Update the context menu style to increase the size of text and icons
- Fix shrinking icon in available connections list
- Update labels for add and remove to use the following:
- "Add node to view"
- "Remove node from view"
- Fix the height of the legend overlay, which was overflowing
- Related to #665 
license.

Update the context menu styles and icons

---

packages/graph-explorer/src/components/IconButton.tsx
packages/graph-explorer/src/components/Panel.tsx
packages/graph-explorer/src/components/Select/internalComponents/SelectBox.tsx
packages/graph-explorer/src/components/Tabular/builders/makeIconActionCell.tsx
packages/graph-explorer/src/components/Tabular/builders/makeIconToggleCell.tsx
packages/graph-explorer/src/components/Tabular/controls/ColumnSettingsControl/ExternalColumnSettingsControl.tsx
packages/graph-explorer/src/components/Tabular/controls/ExternalPaginationControl.tsx
packages/graph-explorer/src/components/Tabular/controls/PaginationControl.tsx
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionData.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/Namespaces/UserPrefixes.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandFilters.tsx
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx

This continues tech debt work to move over to Radix and more standard APIs for our components.
- Removes `as` capability from `IconButton` since it was used in a single place 
- The single use of `as` did not seem to have any impact after it was removed
- Update callers to use standard `button` API for `disabled` and `onClick`
- Verified all select drop down look and behave correctly
- Verify IconButtons continue to work properly
license.

Simplify IconButton to not use react-aria

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/graph-explorer/src/core/ConfigurationProvider/useConfiguration.ts
packages/graph-explorer/src/core/StateProvider/configuration.test.ts
packages/graph-explorer/src/core/StateProvider/configuration.ts
packages/graph-explorer/src/core/StateProvider/displayEdge.test.ts
packages/graph-explorer/src/core/StateProvider/displayEdge.ts
packages/graph-explorer/src/core/StateProvider/displayTypeConfigs.test.ts
packages/graph-explorer/src/modules/EdgesStyling/SingleEdgeStyling.tsx
packages/graph-explorer/src/modules/NodesStyling/SingleNodeStyling.tsx
packages/shared/package.json

Fixes a bug that caused the edge display name to not be shown on the graph.
- Use "types" for value of dropdown option in edge style dialog
- Use attribute types from the edge config (was incorrectly vertex config)
- Add default value for `displayNameAttribute` to default edge config
- Use name & display attribute values from the display config inside the node & edge style dialogs (ensures the correct fallback is used)
- Patch any edge configs that were saved with "type" as the displayNameAttribute to be "types" instead (should be rare, but could happen)
- Updates the version numbers for a patch release
- Added new tests for edge and edge type config
- Verified locally
- Fixes #715 
license.

Fix edge type display

---

Changelog.md
packages/graph-explorer/src/connector/fetchDatabaseRequest.ts

The logic in place for error parsing was not logging the important parts of the error to the console log in the browser. For some reason, Chrome does not print the `cause` field of the error object, as it should.
So, I've added a new log statement that always prints out the error object from the response. Also, I attempt to parse for Neptune errors a bit more generously. So there is a better chance of extracting the message details if the error object contains it.
- Verified by schema sync with my SSH tunnel off so I receive connection refused errors
license.

Better error messages

---

packages/graph-explorer/src/core/StateProvider/displayEdge.test.ts
packages/graph-explorer/src/core/StateProvider/displayVertex.test.ts
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx
packages/graph-explorer/src/modules/SearchSidebar/useKeywordSearch.test.ts
packages/graph-explorer/src/utils/isValidConfigurationFile.ts
packages/graph-explorer/src/utils/testing/randomData.ts
packages/shared/src/types/index.ts

Moves the query engine options to a const array of values and a specific type.
This is a small refactor that I pulled out of another branch for a simple review.
- Smoke test locally
license.

QueryEngine as a type

---

packages/graph-explorer/src/@types/entities.ts
packages/graph-explorer/src/core/StateProvider/entitiesSelector.ts
packages/graph-explorer/src/hooks/useAddToGraph.test.ts
packages/graph-explorer/src/hooks/useEntities.test.tsx

Removes the unused edge count values from `Vertex`. These values are set, but never used by the app.
- Verified expansion and table views
- Part of #710
license.

Remove edge counts

---

packages/graph-explorer/src/connector/gremlin/queries/fetchNeighbors.test.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighborsCount.test.ts
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/hooks/useUpdateNodeCounts.ts
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/utils/testing/randomData.ts

Gremlin queries that are targeting a specific vertex ID need to know both the ID value and the original type (i.e. string or number). This will result in slightly different queries depending on the ID type.
This change is to create a type definition that combines the id value and type in to a single object. This will be more useful in future pull requests.
- Adds `VertexRef` type and updates usages
- Remove unused `neighborsQuery`
- Verified integer ID queries work with Gremlin Server
- Verified string ID queries work Neptune
- Verified neighbor count queries are only executed once per ID
- Part of #710
license.

Combine vertex id and idType

---

Changelog.md
packages/graph-explorer/src/core/AppStatusLoader.tsx
packages/graph-explorer/src/core/ConnectedProvider/ConnectedProvider.tsx
packages/graph-explorer/src/core/defaultConnection.test.ts
packages/graph-explorer/src/core/defaultConnection.ts
packages/graph-explorer/src/index.tsx
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx
packages/graph-explorer/src/utils/testing/randomData.ts
packages/shared/src/types/index.ts

- Move the code that fetches the default connection out of `index.tsx` and in to `AppStatusLoader`.
- Add type for `NeptuneServiceType`
- Add Zod schema for default connection data
- Move default values in to Zod schema
- Add tests
- Use TanStack Query to fetch default connection data
- Show loading screen while fetching default connection
- Add tests for default connection data validation and fallback behavior
- Verified with no default connection and empty database
- Verified with default connection and empty database
- Verified with default connection and existing database
- Verified with no default connection and existing database
- Resolves #732 
- Resolves #634
- Part of #507
license.

Improve default connection logic

---

Changelog.md
packages/graph-explorer/src/core/ConfigurationProvider/types.ts
packages/graph-explorer/src/core/StateProvider/schema.test.ts
packages/graph-explorer/src/hooks/useEntities.ts

Removes the hidden flag on `VertexTypeConfig` and `EdgeTypeConfig` as it was used, but never set.
I went back to the 1.0 code and it seems like it was never set back then as well. Perhaps this was intended to be used as the global type filters that we have today, but the original developers decided to implement the feature differently and didn't cleanup the old code.
- Ensure schema sync still works
- Verified type filters still work
- Verified node & edge filters still work
- Part of #710
license.

Remove hidden flag on schema

---

Changelog.md
packages/graph-explorer/src/core/StateProvider/edges.ts
packages/graph-explorer/src/core/StateProvider/nodes.ts
packages/graph-explorer/src/hooks/index.ts
packages/graph-explorer/src/hooks/useAddToGraph.ts
packages/graph-explorer/src/hooks/useEntities.test.tsx
packages/graph-explorer/src/hooks/useEntities.ts
packages/graph-explorer/src/hooks/useHasVertexBeenAddedToGraph.test.ts
packages/graph-explorer/src/hooks/useHasVertexBeenAddedToGraph.ts
packages/graph-explorer/src/modules/SearchSidebar/NodeSearchResult.tsx
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

This PR finally teases apart some logic that always seemed more complex than it needed to be: `useEntities()`.
- Updated hook for checking if a node is added to the graph
- Renamed to use "vertex" instead of "node" (slowly trying to standardize the codebase on "vertex")
- Moved to its own file
- Added tests
- Check for existence in graph in `nodesAtom` to skip any filters
- Removed unused hook for checking if edge is added to graph
- Updated `useAddToGraph` hook to use `useCallback` to reduce re-renders
- Use `useHasVertexBeenAddedToGraph` in Data Explorer, which was only use of `useEntities({ disableFilters: true })`
- Removed `disableFilters` param from `useEntities`
- Move node and edge filtering logic to Recoil
- Added tests to `useEntities` for filtering
- Verified filtering logic in …

Simplify entities logic

---

packages/graph-explorer/src/@types/entities.ts
packages/graph-explorer/src/connector/gremlin/mappers/detectIdType.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/gremlin/mappers/toStringId.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapIncomingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapOutgoingToEdge.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/core/StateProvider/displayEdge.ts
packages/graph-explorer/src/core/StateProvider/displayVertex.ts
packages/graph-explorer/src/utils/testing/randomData.ts

In order to pull back edge details, we need to have the `idType` defined on the edge. I've updated the code and mapping logic to properly set this data.
- Verified in all three query languages with Neptune
- Verified with Gremlin Server
- Verified with JanusGraph
- Part of #626
license.

Add ID type to Edge

---

packages/graph-explorer/src/core/StateProvider/userPreferences.ts
packages/graph-explorer/src/modules/EdgesStyling/EdgesStyling.tsx
packages/graph-explorer/src/modules/EntitiesFilter/EntitiesFilter.tsx
packages/graph-explorer/src/modules/EntitiesFilter/index.ts
packages/graph-explorer/src/modules/EntityDetails/EntityDetails.tsx
packages/graph-explorer/src/modules/EntityDetails/index.ts
packages/graph-explorer/src/modules/Namespaces/Namespaces.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpand.tsx
packages/graph-explorer/src/modules/NodeExpand/index.ts
packages/graph-explorer/src/modules/NodesStyling/NodesStyling.tsx
packages/graph-explorer/src/modules/SearchSidebar/SearchSidebar.tsx
packages/graph-explorer/src/modules/SidebarCloseButton.tsx
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx

The sidebar close button callback was being passed in to each sidebar component. Instead I abstract a shared component called `SidebarCloseButton` that handles it all without having to pass any props.
- Verified sidebars still open and close
license.

Abstract out SidebarCloseButton

---

Changelog.md
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/core/StateProvider/neighbors.ts
packages/graph-explorer/src/core/connector.ts
packages/graph-explorer/src/hooks/useAddToGraph.test.ts
packages/graph-explorer/src/hooks/useAddToGraph.ts
packages/graph-explorer/src/hooks/useEdgeDetailsQuery.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/hooks/useRemoveFromGraph.test.ts
packages/graph-explorer/src/hooks/useRemoveFromGraph.ts
packages/graph-explorer/src/hooks/useSchemaSync.ts
packages/graph-explorer/src/hooks/useUpdateNodeCounts.ts
packages/graph-explorer/src/hooks/useUpdateVertexTypeCounts.ts
packages/graph-explorer/src/hooks/useVertexDetailsQuery.ts
packages/graph-explorer/src/modules/EntitiesTabular/components/NodesTabular.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/internalComponents/ContextMenu.tsx
packages/graph-explorer/src/modules/GraphViewer/useNodeBadges.ts
packages/graph-explorer/src/modules/SearchSidebar/NodeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/SearchResultsList.tsx
packages/graph-explorer/src/modules/SearchSidebar/useKeywordSearchQuery.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

Moves manipulation of the `entitiesSelector` Recoil state behind domain specific hooks. This will aid in the switch to entity ID as a base for the graph.
- Add `useExplorer()` hook to abstract away dependency on Recoil
- Update `useAllNeighbors()` hook to get the graph entities internally
- Add `useClearGraph()` to remove all entities from the graph (used in `GraphViewer` and `ContextMenu`)
- Update `useRemoveFromGraph()` to push the parameters in to the callback function
- Updated the convenience hooks to call the one main hook
- Update `useAddToGraph()` to pass the entities to the callback
- Change the convenience hook `useAddVertexToGraph()` to us the main hook
- Ensure `useExpandNode()` uses `useAddToGraph()`
- For neighbor count and expansion queries, get the expansion limit set on …

Reduce dependence on Recoil and useEntities()

---

packages/graph-explorer/src/components/Graph/hooks/useRenderBadges.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/connector/sparql/types.ts
packages/graph-explorer/src/core/StateProvider/edges.ts
packages/graph-explorer/src/core/StateProvider/neighbors.ts
packages/graph-explorer/src/core/StateProvider/nodes.ts
packages/graph-explorer/src/core/entities.ts
packages/graph-explorer/src/core/entityIdType.test.ts
packages/graph-explorer/src/core/entityIdType.ts
packages/graph-explorer/src/core/index.ts
packages/graph-explorer/src/core/renderedEntities.test.ts
packages/graph-explorer/src/core/renderedEntities.ts
packages/graph-explorer/src/hooks/useUpdateNodeCounts.ts
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/useContextMenu.ts
packages/graph-explorer/src/modules/GraphViewer/useGraphStyles.ts
packages/graph-explorer/src/modules/GraphViewer/useNodeBadges.ts
packages/graph-explorer/src/modules/SearchSidebar/useKeywordSearchQuery.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

Updates the logic to allow `VertexId` and `EdgeId` to be either `string` or `number`. This requires a workaround to interface with Cytoscape, since they require the IDs to be a `string`.
So I've introduced `RenderedVertex` and `RenderedEdge` that map the IDs to string with the prefixed type encoded.
- Verified across all query languages
- Resolves #771 
license.

Rollback serialized id type

---

Changelog.md
packages/graph-explorer/src/connector/emptyExplorer.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/core/connector.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/hooks/useSchemaSync.ts

Ensure that the code that requests an `Explorer` instance always receives a value. When there is no active connection, use an `emptyExplorer` instance that simply returns empty results for any function calls.
This fixes an app crash bug (#774) that I introduced in a recent change. It also allowed me to clean up some null checking code that is no longer necessary.
- Smoke tested
- Fixes #774 
license.

Make sure Explorer always has a value

---

Changelog.md
packages/graph-explorer/package.json
packages/graph-explorer/src/components/FileButton.tsx
packages/graph-explorer/src/components/Graph/hooks/useRunLayout.ts
packages/graph-explorer/src/components/index.ts
packages/graph-explorer/src/modules/GraphViewer/ExportGraphButton.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/ImportGraphButton.test.tsx
packages/graph-explorer/src/modules/GraphViewer/ImportGraphButton.tsx
packages/graph-explorer/src/modules/GraphViewer/exportedGraph.test.ts
packages/graph-explorer/src/modules/GraphViewer/exportedGraph.ts
packages/graph-explorer/src/utils/fileData.ts
packages/graph-explorer/src/utils/testing/randomData.ts
packages/graph-explorer/tsconfig.app.json
packages/shared/src/types/index.ts
pnpm-lock.yaml

Adds the ability to save and load a graph to and from a file. This requires the user to be in the same connection. We define "the same" as:
- Same database URL (regardless of proxy server use)
- Same query engine (i.e. Gremlin, openCypher, SPARQL)
The file contains a minimal set of information needed to reconstruct the graph:
- Metadata
- Kind of document
- Source of export (i.e. Graph Explorer)
- Version of the source (i.e. Graph Explorer version)
- Timestamp
- Connection
- Graph database URL
- Query engine
- Graph data
- List of node IDs
- List of edge IDs
During import, the file will be validated with Zod, then sent to the vertex and edge details queries to load the data. When all those queries return back it will render the graph.
The export path will attempt to use the new file …

Export and import graph

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/edgeDetails.test.ts
packages/graph-explorer/src/connector/gremlin/vertexDetails.test.ts
packages/graph-explorer/src/connector/openCypher/edgeDetails.test.ts
packages/graph-explorer/src/connector/openCypher/idParam.ts
packages/graph-explorer/src/connector/openCypher/vertexDetails.test.ts
packages/graph-explorer/src/connector/sparql/createRdfEdgeId.ts
packages/graph-explorer/src/connector/sparql/edgeDetails.test.ts
packages/graph-explorer/src/connector/sparql/edgeDetails.ts
packages/graph-explorer/src/connector/sparql/idParam.ts
packages/graph-explorer/src/connector/sparql/mappers/mapIncomingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapOutgoingToEdge.ts
packages/graph-explorer/src/connector/sparql/types.ts
packages/graph-explorer/src/connector/sparql/vertexDetails.test.ts
packages/graph-explorer/src/connector/sparql/vertexDetails.ts
packages/graph-explorer/src/modules/GraphViewer/ImportGraphButton.test.tsx
packages/graph-explorer/src/modules/GraphViewer/ImportGraphButton.tsx
packages/graph-explorer/src/modules/GraphViewer/exportedGraph.test.ts
packages/graph-explorer/src/modules/GraphViewer/exportedGraph.ts
packages/graph-explorer/src/utils/testing/randomData.ts

This change helps prevent the chances of an injection attack through the saved graph file.
In the process of importing the graph file we now do some basic sanity checks on the vertex and edge IDs.
- Trim any leading or trailing whitespace
- Ensure they are not empty string
- If property graph, escape strings
- If RDF, ensure no `>` exist
- If RDF, ensure edge format is correct
- Fixed toast notification where 1 node or edge was not found (said "were" instead of "was")
- Removed `idType` that was no longer necessary
- Verified export and import still work properly
- Verified modified exported graph files fail gracefully
- Fixes #789 
license.

Escape entity details queries

---

Changelog.md
packages/graph-explorer/src/core/AppStatusLoader.tsx
packages/graph-explorer/src/core/ConfigurationProvider/types.ts
packages/graph-explorer/src/core/StateProvider/configuration.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx

Removes the logic that disabled some fields on the edit connection modal and disabled the delete button.
- Ensured existing default connections are no longer disabled
- Ensured newly created default connections are no longer disabled
- Resolves #800 
license.

Remove logic that disables fields on default connection

---

additionaldocs/getting-started/README.md

The https-connections section was moved under troubleshooting.md but the link is pointing to the old https-connections section which does not exist
Fix https-connections link in documentation.
The https-connections section was moved under troubleshooting.md but the link is pointing to the old https-connections section which does not exist.
Manual Validation
license.

fix: https-connections link in documentation

---

Changelog.md
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx

Update the service type drop down to be "Neptune Analytics" instead of "Neptune Graph".
I searched the codebase for any other occurrences, but I didn't find any.
- Resolves #798
license.

Update label to be Neptune Analytics (not Graph)

---

Changelog.md
packages/graph-explorer-proxy-server/src/error-handler.ts
packages/graph-explorer-proxy-server/src/logging.ts
packages/graph-explorer-proxy-server/src/node-server.ts
packages/graph-explorer/src/connector/LoggerConnector.ts
packages/graph-explorer/src/connector/fetchDatabaseRequest.ts
packages/graph-explorer/src/core/ConnectedProvider/ConnectedProvider.tsx
packages/graph-explorer/src/core/StateProvider/schema.ts
packages/graph-explorer/src/hooks/usePrefixesUpdater.ts
packages/graph-explorer/src/modules/Namespaces/GeneratedPrefixes.tsx
packages/graph-explorer/src/utils/NetworkError.ts
packages/graph-explorer/src/utils/createDisplayError.test.ts
packages/graph-explorer/src/utils/createDisplayError.ts
packages/graph-explorer/src/utils/index.ts

This PR has a grab bag of changes, but mostly focused around error handling during fetch requests.
- Fix "Delete Schema" debug action (it wasn't actually deleting it)
- Client side logging
- Add support for timeout errors in `createDisplayError()`
- Ensure all errors that happen within TanStack Query are logged
- Log to the browser console when the `ServerLogger` fails (prevents an uncaught Promise error)
- Add some extra safety around decoding error response payloads (handles non-JSON responses better)
- Add `NetworkError` type so that the status code and parsed error can be included
- Use `NetworkError` in `fetchDatabaseRequest()`
- Handle `NetworkError` in `createDisplayError()`
- Prevent retrying in TanStack Query when the network response is in a given set of status codes (i.e. 401, …

Better error handling for database requests

---

Changelog.md
packages/graph-explorer/src/core/AppStatusLoader.tsx
packages/graph-explorer/src/core/defaultConnection.ts
packages/graph-explorer/src/hooks/useDeleteConfig.test.ts
packages/graph-explorer/src/hooks/useDeleteConfig.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx
packages/shared/src/types/index.ts

There is an issue that seems to occur in a specific scenario:
1. Open Graph Explorer for the first time
2. Default connections created
3. Delete default connection
It should delete the connection, but instead it immediately recreates the deleted connection. Further deletions work correctly.
To fix, I rearranged the logic in the `AppStatusLoader` effect.
- Update default connection query to generate one connection per query engine, unless a specific query engine is specified
- Check if any connections exist, if so skip default connection logic
- Check if any default connections were received from the server, if not skip
- Add all default connections to the connections storage
- Set first connection as active
- Reorder the query engine options to put the property graph options together and …

Fix deleting default connections

---

Changelog.md
packages/graph-explorer/src/components/VertexRow.tsx
packages/graph-explorer/src/utils/replacePrefixes.test.ts
packages/graph-explorer/src/utils/replacePrefixes.ts

Fixes two issues:
- Ensure long text is wrapped no matter what on search result items to ensure the add to graph button is visible
- Update `replacePrefix()` to ignore case for its matching
- Also include generated prefixes that only match a single type
- Tested in RDF dataset
- Resolves #823 
license.

Fix search result wrapping

---

README.md

The current docs assume the base Docker registry is ECR, while for most users it will lead to DockerHub, where the image does not exist

Update README.md to point to the right ECR docker image

---

Changelog.md
README.md
packages/graph-explorer-proxy-server/src/node-server.ts
packages/graph-explorer/vite.config.ts

Add a new `/status` endpoint to get the health of proxy
- Checked by building the image locally and hitting the `/status` endpoint
Fixes #765
license.

feat: add /status endpoint to verify proxy health

---

Changelog.md
packages/graph-explorer/src/components/Input.tsx
packages/graph-explorer/src/components/InputField/InputField.tsx
packages/graph-explorer/src/components/TextArea/TextArea.tsx
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx
packages/graph-explorer/tailwind.config.ts

Fixes issue that I introduced in #832 where the Aria hooks don't like when you don't provide a proper label for input fields.
This is the simple fix for the issue: provide an `aria-label` for each input. I have a much larger change that converts the create connection modal to use React Hook Form instead. But that code needs a bit more testing before I push it up.
- Added `aria-invalid` to Tailwind config so I can style with it
- Use `aria-invalid` in `Input` and `TextArea` to style with red border
> If you do not provide a visible label, you must specify an aria-label or aria-labelledby attribute for accessibility Error Component Stack
- Verified all inputs and text areas have labels and no more warnings in the console
- PR #832
license.

Fix console warnings for missing aria-label

---

packages/graph-explorer/src/connector/gremlin/fetchNeighbors/index.test.ts
packages/graph-explorer/src/connector/gremlin/fetchNeighbors/oneHopTemplate.ts
packages/graph-explorer/src/connector/openCypher/fetchNeighbors/oneHopTemplate.ts
packages/graph-explorer/src/connector/sparql/mappers/mapRawResultToVertex.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/sparql/vertexDetails.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/core/StateProvider/displayVertex.test.ts
packages/graph-explorer/src/core/entities.ts
packages/graph-explorer/src/core/renderedEntities.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/utils/testing/randomData.ts

Simplifies the expand node api just a bit by removing the need to send a full `Vertex` object.
Expanding a node only requires the vertex ID. Except for SPARQL. It requires the `vertexType` as well, which is used to path `Edge` instances during mapping with the source vertex type.
In the future I will remove the need to send the `vertexType` entirely when I redo all SPARQL queries. For now it remains
- Tested on all three query engines
- Tangentially related to #808
license.

Don’t require full vertex for expand

---

Changelog.md
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx

Fixes an issue where the previous session is presented as available after changing the connection URL or query engine. If you attempt to restore this session it will fail.
The change was to ensure the previous session data is deleted when a connection is changed, specifically the proxy URL, database URL, or query engine.
- Ensured editing a connection by changing url/db url/query engine would cause session data to be deleted
- Ensured changing other fields do not affect session data
- Resolves #836 
license.

Delete previous session on connection changes

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/edgeDetails.test.ts
packages/graph-explorer/src/connector/gremlin/edgeDetails.ts
packages/graph-explorer/src/connector/gremlin/fetchNeighbors/index.test.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiVertex.test.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapResults.test.ts
packages/graph-explorer/src/connector/gremlin/vertexDetails.test.ts
packages/graph-explorer/src/connector/gremlin/vertexDetails.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiEdge.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.test.ts
packages/graph-explorer/src/connector/openCypher/mappers/mapApiVertex.ts
packages/graph-explorer/src/connector/sparql/edgeDetails.ts
packages/graph-explorer/src/connector/sparql/mappers/mapIncomingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapOutgoingToEdge.ts
packages/graph-explorer/src/connector/sparql/mappers/mapRawResultToVertex.ts
packages/graph-explorer/src/connector/sparql/vertexDetails.ts
packages/graph-explorer/src/core/createEntities.test.ts
packages/graph-explorer/src/core/createEntities.ts
packages/graph-explorer/src/core/entities.ts
packages/graph-explorer/src/core/index.ts
packages/graph-explorer/src/modules/SearchSidebar/EdgeSearchResult.tsx
packages/graph-explorer/src/utils/testing/graphsonHelpers.ts
packages/graph-explorer/src/utils/testing/randomData.ts

Instead of creating `Vertex` or `Edge` instances from scratch, I've changed it to use a factory method. This abstracts the intricacies of the type in to the factory function, such as how the fragment flag is determined and how type vs types are handled.
This also allows easier modification of the `Vertex` and `Edge` type structures in the future.
- Adds `createVertex()` and `createEdge()` functions
- Updates all creation sites to use new functions
- Add tests to ensure `__isFragment` is set correctly
- Make `__isFragment` and `__isBlank` non-optional
- Smoke tested all three query languages
- Part of #845
license.

Create entity functions

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/mappers/mapResults.test.ts
packages/graph-explorer/src/connector/gremlin/mappers/mapResults.ts
packages/graph-explorer/src/hooks/index.ts
packages/graph-explorer/src/hooks/useAddToGraph.test.ts
packages/graph-explorer/src/hooks/useAddToGraph.ts
packages/graph-explorer/src/hooks/useDisplayVertexFromFragment.ts
packages/graph-explorer/src/hooks/useMaterializeVertices.ts
packages/graph-explorer/src/modules/SearchSidebar/EdgeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/NodeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/SearchResultsList.tsx

- Expands edges added to the graph to include the vertices as fragments
- Expands edges in query results to include the vertices as fragments
- Fetches details for any fragments before adding to graph
- Fetches details in search results for any fragments
- Tested locally with gremlin queries
- Smoke tested other query languages
- Resolves #845
license.

Enhanced query logic

---

Changelog.md
packages/graph-explorer/package.json
packages/graph-explorer/src/components/Dialog.tsx
packages/graph-explorer/src/components/PanelError.tsx
packages/graph-explorer/src/components/index.ts
pnpm-lock.yaml

Adds a new "Error Details" button to error panels to open a dialog with the full message from the error.
- Convert `PanelError` to use basic `EmptyState` components
- Add radix dialog component and styles (this is part of #701)
- Part of #701 
- Resolves #856 
license.

Add ability to see full error message

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/fetchNeighbors/index.test.ts
packages/graph-explorer/src/connector/gremlin/fetchNeighborsCount/index.test.ts
packages/graph-explorer/src/connector/gremlin/fetchSchema/index.test.ts
packages/graph-explorer/src/connector/gremlin/keywordSearch/index.test.ts
packages/graph-explorer/src/connector/testUtils/globalMockFetch.ts
packages/graph-explorer/src/setupTests.ts

- Makes `globalMockFetch` helper in to an explicit stub of specific response files
- The old code used a generated hash of the query string being submitted to find the file to use as the response. This was extremely fragile because any single character change in the query would cause these tests to break. It was then very difficult to determine which hash code to update to "fix" the tests.
- Ensure all global stubs are reset after each test
- Move `localforage` mock out of `beforeEach` since Vitest hoists that code to the global scope no matter where it is placed.
- Add global mock for `logger` so that when running tests nothing is printed to the standard out, making the test results much easier to comprehend
- All tests pass
- No log statements are produced in test output …

Make tests less fragile

---

Changelog.md
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/hooks/useSchemaSync.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx

Adds cancel button for long running schema sync.
license.

Add ability to cancel schema sync

---

Changelog.md
packages/graph-explorer/src/connector/sparql/edgeDetails.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/helpers.test.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/helpers.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/index.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/mapToResults.test.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/mapToResults.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/oneHopNeighborsBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/oneHopNeighborsTemplate.test.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/oneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/fetchNeighborsCount/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/sparql/fetchNeighborsCount/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/sparql/getLimit.test.ts
packages/graph-explorer/src/connector/sparql/getLimit.ts
packages/graph-explorer/src/connector/sparql/idParam.ts
packages/graph-explorer/src/connector/sparql/keywordSearch/keywordSearchBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/keywordSearch/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/sparql/keywordSearch/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/sparql/parseEdgeId.test.ts
packages/graph-explorer/src/connector/sparql/parseEdgeId.ts
packages/graph-explorer/src/connector/sparql/types.ts
packages/graph-explorer/src/modules/GraphViewer/exportedGraph.ts
packages/graph-explorer/src/utils/sanitizeQuery.test.ts
packages/graph-explorer/src/utils/sanitizeQuery.ts
packages/graph-explorer/src/utils/testing/normalize.ts

Fixes issues with neighbor expansion in RDF databases. It uses a single query to retrieve the following information using subqueries and unions:
- Distinct neighbors of source
- Filter by class
- Filter by property value
- Limit results
- Edges between neighbor and source in both directions
- Neighbor properties and classes
- Resource classes of source
- Property value filter not working
- Neighbor counts inconsistent (only sometimes correct)
- Limit properly applied to neighbor list before getting to edges
- [Remaining neighbor count issues with multi-label](#746)
- RDF handling of multi-label in other queries
- I don't think multi-label in RDF was ever officially supported
- Moved `parseEdgeId` function out of `types.ts` file
- Update `idParam` to accept a plain string param
- Verified …

Fix RDF neighbor expansion

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/fetchNeighbors/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/fetchNeighbors/oneHopTemplate.ts
packages/graph-explorer/src/connector/openCypher/fetchNeighbors/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/fetchNeighbors/oneHopTemplate.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/oneHopNeighborsTemplate.test.ts
packages/graph-explorer/src/connector/sparql/fetchNeighbors/oneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/sparql/types.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/core/StateProvider/neighbors.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx

Fixes an issue with double click to expand explained in issue #462.
Expansion can now have a list of excluded nodes that are added to the query to skip.
- Verified in air routes with all three query languages
- Verified in premiere league RDF data set with blank nodes
- Resolves #462
license.

Exclude existing neighbors in double click expansion

---

Changelog.md
packages/graph-explorer-proxy-server/src/node-server.ts

If a request to the proxy server is interrupted in the middle of piping the database response back, then we will fire the pipeline error handler. This was attempting to set the response status on a closed stream, which results in an error.
Instead, I now just log the error as a warning since the error doesn't actually cause any true harm. It no longer attempts to modify the response at all.
- Verified locally with a query that is aborted milliseconds after the request is created
- Resolves #861
license.

Fix server side error when a query is cancelled

---

Changelog.md
packages/graph-explorer/src/components/CheckboxList.tsx
packages/graph-explorer/src/core/StateProvider/schema.ts
packages/graph-explorer/src/modules/EdgesStyling/EdgeStyleDialog.tsx
packages/graph-explorer/src/modules/EdgesStyling/EdgesStyling.tsx
packages/graph-explorer/src/modules/EdgesStyling/SingleEdgeStyling.tsx
packages/graph-explorer/src/modules/EdgesStyling/index.ts
packages/graph-explorer/src/modules/EntitiesFilter/EntitiesFilter.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/index.ts
packages/graph-explorer/src/modules/GraphViewer/internalComponents/ContextMenu.tsx
packages/graph-explorer/src/modules/NodesStyling/NodeStyleDialog.tsx
packages/graph-explorer/src/modules/NodesStyling/NodesStyling.tsx
packages/graph-explorer/src/modules/NodesStyling/SingleNodeStyling.tsx
packages/graph-explorer/src/modules/NodesStyling/index.ts
packages/graph-explorer/src/utils/generatePrefixes.test.ts
packages/graph-explorer/src/utils/generatePrefixes.ts
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx

* Adding and expanding nodes
* The issue was updating prefixes doing too much work
* Optimized now to nearly be instant
* Entity styles
* Two issues: large list rendering & duplicate dialog instances
* Large list is now virtualized
* Dialog is now condensed to a single instance that changes based on the selected vertex types
* Moved dialog open state in to Recoil
* Entity filters
* The issue is large list rendering
* Split vertex and edges in to separate tabs
* Large list is now virtualized
* Required tweaking the UI a bit to allow for virtualization
- Used browser's CPU throttling at 4x and 6x for testing
- Used dataset with 500 node labels
- Resolves #886
license.

Fix performance issues in generatePrefixes

---

Changelog.md
packages/graph-explorer/src/connector/sparql/fetchSchema/index.ts

Exclude RDF metadata types from class list during schema sync.
- Validated with RDF database in Neptune that includes OWL metadata classes
- Validated with Air Routes in Neptune (no metadata classes)
- Resolves #902
license.

Exclude metadata types from schema sync

---

Changelog.md
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx

When certain parts of the connection config changes, we should dump all the cached values in TanStack Query. This will cause a schema sync to automatically fire.
- Tested by updating existing connection changing query engine, URL, or DB URL
- Tested by updating existing connection changing any other property
- Tested by creating a new connection
- Resolves #914 
license.

Fix auto sync on connection change

---

Changelog.md
packages/graph-explorer/babel.config.js
packages/graph-explorer/src/connector/emptyExplorer.ts
packages/graph-explorer/src/connector/fetchDatabaseRequest.ts
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/openCypher/openCypherExplorer.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/core/StateProvider/configuration.test.ts
packages/graph-explorer/src/core/StateProvider/configuration.ts
packages/graph-explorer/src/core/connector.ts

The original `ConnectionConfig` type has many fields that are marked as optional. But once the app is using the connection it has been transformed to not have so many optional fields. But since the type is defined as optional, the code had to deal with those optionals.
So I'm adding a new type `NormalizedConnection` that does not have all the optionals.
- Smoke test
- Part of #572
license.

Use a normalized connection type to reduce optionals

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/fetchNeighborsCount/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/fetchNeighborsCount/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/openCypher/fetchNeighbors/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/fetchNeighbors/oneHopTemplate.ts
packages/graph-explorer/src/connector/openCypher/fetchNeighborsCount/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/fetchNeighborsCount/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/connector/sparql/fetchNeighborsCount/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/sparql/fetchNeighborsCount/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/sparql/types.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/utils/sanitizeQuery.ts

- Removes limit placed on neighbor count queries
- This didn't have a good reason to exist
- Update openCypher fetch neighbors query
- Remove unnecessary `WITH` line, moving the logic to `RETURN`
- Add slimmed down faster query when no limit is provided
- Update `query` tagged template literal to take `unknown` parameters instead of only `string`
- These get converted to string within the function
- Tested openCypher extensively with different filter options
- Related to #572
license.

Update expansion queries

---

packages/graph-explorer-proxy-server/src/env.ts
packages/graph-explorer-proxy-server/src/node-server.ts
process-environment.sh

This MR adds support for configuring the folder path where the .env and defaultConnection.json files are read from and written to. This solves an issue when Graph Explorer is deployed in ECS with read-only root volume enabled, by allowing these configuration files to be stored in a writable location.
The changes introduce a new environment variable `CONFIGURATION_FOLDER_PATH` that specifies where these configuration files should be located. If not specified, the system falls back to the default client root path.
The changes have been tested by:
Setting the CONFIGURATION_FOLDER_PATH environment variable to different locations
Verifying that the application correctly reads the .env and defaultConnection.json files from the specified location
Confirming that the application still works …

Add configurable path for .env and defaultConnection.json files

---

Changelog.md
packages/graph-explorer/src/connector/emptyExplorer.ts
packages/graph-explorer/src/connector/gremlin/gremlinExplorer.ts
packages/graph-explorer/src/connector/gremlin/rawQuery.ts
packages/graph-explorer/src/connector/openCypher/openCypherExplorer.ts
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/connector/sparql/sparqlExplorer.ts
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/core/StateProvider/useResetState.ts
packages/graph-explorer/src/modules/SearchSidebar/QuerySearchTabContent.tsx
packages/graph-explorer/src/modules/SearchSidebar/SearchSidebar.tsx
packages/graph-explorer/src/utils/testing/createMockExplorer.ts

This reverts commit 8ba891985fce12e45be581a08fda258371faf5a6.
This PR targets [aws:main-query-editor](https://github.com/aws/graph-explorer/tree/main-query-editor) branch instead of `main`.
I simply reverted the single commit from PR #862 and modified the changelog to account for conflicts. No other file had any conflicts, so they remain the same as when they were removed.
I also removed the feature flag since this is on its own branch, and updated the code to use Jotai instead of Recoil.
- Smoke test
- Resolves #863
license.

Re-add query editor for Gremlin

---

Changelog.md
packages/graph-explorer/package.json
packages/graph-explorer/src/components/ColorInput/ColorInput.tsx
packages/graph-explorer/src/components/Input.tsx
packages/graph-explorer/src/modules/EdgesStyling/EdgeStyleDialog.tsx
packages/graph-explorer/src/modules/NodesStyling/NodeStyleDialog.tsx
pnpm-lock.yaml

Continuing the slow process of removing Mantine. This change uses [react-colorful](https://omgovich.github.io/react-colorful/), a very popular library for picking colors.
I considered using the browser's built in color picker, but browser support and OS support is still a little spotty.
The library offers a HEX input that handles all the validation logic, so the existing logic was removed.
You'll also notice that there is an input inside the popover. This is because the old color input had dueling focus issues. You'd click on the input to type, then the popover would show up and steal the focus. So you'd have to click again to dismiss the popover in order to type in the input.
So, to make the UX better (but the UI a little worse), I added the input in to the popover and made the outer …

Use react-colorful for ColorInput

---

Changelog.md
packages/graph-explorer/src/components/FileButton.tsx
packages/graph-explorer/src/modules/AvailableConnections/AvailableConnections.tsx
packages/graph-explorer/src/modules/GraphViewer/ImportGraphButton.tsx
packages/graph-explorer/src/modules/NodesStyling/NodeStyleDialog.tsx
packages/graph-explorer/src/workspaces/Settings/LoadConfigButton.tsx

Use internal `FileButton` component rather than the Mantine provided one.
- Add `resetRef` to allow clearing the file input state imperatively
- Updated `onChange` to be specific to multiple or single files
- Use the HTML standard `disabled` instead of the React Aria `isDisabled` 
- Update usages of `FileButton` to use the slightly updated API
- For reviewing, you should ignore whitespace
- Tested all file buttons in the app
- No UI or behavior change
- Resolves #729
license.

Use internal FileButton instead of Mantine

---

Changelog.md
packages/graph-explorer/src/core/StateProvider/StateProvider.tsx
packages/graph-explorer/src/core/StateProvider/index.ts
packages/graph-explorer/src/core/StateProvider/userLayout.ts
packages/graph-explorer/src/core/StateProvider/userPreferences.test.ts
packages/graph-explorer/src/core/StateProvider/userPreferences.ts
packages/graph-explorer/src/modules/EdgesStyling/EdgeStyleDialog.tsx
packages/graph-explorer/src/modules/EdgesStyling/SingleEdgeStyling.tsx
packages/graph-explorer/src/modules/EntityDetails/EntityDetails.tsx
packages/graph-explorer/src/modules/GraphViewer/internalComponents/ContextMenu.tsx
packages/graph-explorer/src/modules/GraphViewer/useAutoOpenDetailsSidebar.ts
packages/graph-explorer/src/modules/NodesStyling/NodeStyleDialog.tsx
packages/graph-explorer/src/modules/NodesStyling/SingleNodeStyling.tsx
packages/graph-explorer/src/utils/testing/DbState.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx

Fixes a bug in the saving logic for node & edge preferences.
Before the fix, the user-styling storage would be overwritten with a single node or edge preference, rather than updating the list of node and edge preferences.
After finding the bug, I moved all logic related to updating the user preferences in to `userPreferences.ts` and added some tests.
- Tested setting styles in sidebar (node & edge)
- Tested setting style in Data Explorer
- Resolves #935
license.

Fix saving entity preferences

---

Changelog.md
packages/graph-explorer/src/components/Workspace/components/WorkspaceSideBar.tsx
packages/graph-explorer/src/components/Workspace/components/WorkspaceSideBarContent.tsx
packages/graph-explorer/src/core/StateProvider/userLayout.test.ts
packages/graph-explorer/src/core/StateProvider/userLayout.ts
packages/graph-explorer/src/modules/SidebarCloseButton.tsx
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx

Adds the ability to resize the sidebar using a gripper on the left side.
* Disable resizing when sidebar is closed
* Persist size in user layout preferences
* Disable transition animation when resizing since it makes the resize feel laggy
- Tested in Arc (chrome) and Safari
https://github.com/user-attachments/assets/e8563758-5e11-4829-8b09-7b118816edf2
- Resolves #937 
license.

Allow resizing the sidebar

---

Changelog.md
packages/graph-explorer/src/hooks/useAddToGraph.test.ts
packages/graph-explorer/src/hooks/useAddToGraph.ts
packages/graph-explorer/src/hooks/useMaterializeEdges.test.ts
packages/graph-explorer/src/hooks/useMaterializeEdges.ts
packages/graph-explorer/src/hooks/useMaterializeVertices.test.ts
packages/graph-explorer/src/modules/SearchSidebar/EdgeSearchResult.tsx
packages/graph-explorer/src/utils/testing/index.ts

When a query returns a path with an edge, the edge is a fragment. While we are correctly materializing vertices, we were not materializing edges.
This change is basically a copy of what we are doing with vertices.
- Tested using query in #971 
- Resolves #971 
license.

Ensure edge details are materialized

---

Changelog.md
packages/graph-explorer/src/components/Graph/Graph.model.ts
packages/graph-explorer/src/components/Graph/Graph.tsx
packages/graph-explorer/src/components/Graph/helpers/layout.ts
packages/graph-explorer/src/components/Graph/helpers/layoutConfig.ts
packages/graph-explorer/src/components/Graph/hooks/useRunLayout.ts
packages/graph-explorer/src/components/Select.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/SelectLayout.tsx

- Made layout configs more type safe
- Renamed hierarchical and subway directions
- Added bottom to top and right to left directions
- Moved layout select to its own component
- Use Jotai state for layout selection so it persists at a session level
https://github.com/user-attachments/assets/2a4b9d03-d191-4d3a-83de-41efd609d2a7
- Resolves #972 
license.

Update layout options

---

Changelog.md
packages/graph-explorer/src/utils/createDisplayError.test.ts
packages/graph-explorer/src/utils/createDisplayError.ts

Updates too many request message so that the database does not take the blame. Most likely the requests are throttled elsewhere before hitting the database.
- Resolves #977
license.

Update too many requests message

---

Changelog.md
packages/graph-explorer/src/components/Label.tsx
packages/graph-explorer/src/modules/EntityDetails/EdgeDetail.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandFilters.tsx
packages/graph-explorer/src/modules/SearchSidebar/EdgeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/NodeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/SearchResultsList.tsx
packages/graph-explorer/src/modules/common/NeighborsList/NeighborsList.tsx

The use of borders at the bottom of rows was not rendering properly sometimes. My theory is that some overlapping of elements was occurring. Instead, we use the Tailwind standard way of applying separators, using `divide-y divide-{color}`. This seems to render properly in all cases.
- Added separator in edge detail panel between edge representation and properties
- Tweaked spacing and style of neighbor list header
- Tweaked spacing of neighbor expansion options
- Added title to neighbor expansion options section
- In search results that expand to show attributes (node and edge) I allow the attribute to stretch to the right edge, only indenting on the left
- Tweaked `Label` to reduce font weight to baseline since medium was looking a bit heavy
- Resolves #994 
license.

Fix row separator in search results

---

Changelog.md
packages/graph-explorer/src/components/LoadingSpinner/LoadingSpinner.tsx
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx

I saw this pattern and knew it would be easy to implement and could be useful.
The spinner component can now wrap another component. When the `loading` flag is true the spinner is shown instead of the wrapped component. No layout shift will occur.
My inspiration came from [Radix UI](https://www.radix-ui.com/blog/themes-3#spinner).
- Changed the sync icon in the connection details to use this style to verify it works propeerly
- Tested other uses of spinner to make sure they still work correctly
- None
license.

Add ability to wrap component with spinner

---

.vscode/settings.json
Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
tsconfig.json
tsconfig.root.json
vitest.config.ts
vitest.workspace.ts

I removed the old `vitest.workspaces.ts` and added a `vitest.config.ts`. This change is documented in the [Vitest documentation](https://vitest.dev/guide/projects).
- Added `vitest.config.ts` to TypeScript type checking by adding a new `tsconfig.root.json`
- Moved the TypeScript cleaning to the root so that the new root level typescript config build info will be cleaned up properly
- Changed `check:types` to use incremental building for the performance wins
- If this becomes an issue we can always go back to `--force`
- If needed, `pnpm clean && pnpm check:types` is the same as `--force`
- Make Prettier the default formatter for all files in VS Code
- Tested checking types
- Tested running tests
- Tested building
- Tested cleaning
- Resolves #1018 
license.

Migrate vitest workspaces

---

Changelog.md
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionData.tsx

Renamed the label from "attributes" to "properties" or "predicates" depending on connection type.
- Resolves #1029
license.

Rename labels in connection detail for properties

---

Changelog.md
packages/graph-explorer/src/modules/SearchSidebar/QuerySearchTabContent.tsx

The no results message can be a bit confusing when executing mutations that would not have any results returned. So I modified the message to show that the query succeeded.
- Resolves #1032
license.

Improve the no results message for the query editor

---

packages/graph-explorer/src/core/StateProvider/neighbors.ts
packages/graph-explorer/src/core/fetchEntityDetails.ts
packages/graph-explorer/src/hooks/useMaterializeEdges.ts
packages/graph-explorer/src/hooks/useMaterializeVertices.ts

I was using the `ensureQueryData` function to fetch query data imperatively. This will not use cached data if it exists and will always fetch new data.
Instead, we should use `fetchQuery` so that if there is valid cached data it will be used.
Smoke tested
- N/A
license.

Use fetchQuery instead of ensureQueryData

---

packages/graph-explorer/src/connector/gremlin/mappers/mapResults.ts
packages/graph-explorer/src/core/entities/scalar.test.ts
packages/graph-explorer/src/core/entities/scalar.ts
packages/graph-explorer/src/modules/SearchSidebar/ScalarSearchResult.tsx

Removes the complex discriminated union type, which caused some TypeScript headaches for some future changes.
Instead, use simple value type inference to mimic the same behavior.
- Teste with query editor
- Part of #1087
license.

Simplify Scalar type

---

packages/graph-explorer/src/connector/gremlin/fetchNeighbors/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/fetchNeighbors/oneHopTemplate.ts

The `.order().by(id())` in the neighbor fetch for gremlin was unnecessary. It did provide some amount of stability for the returned results when double clicking, but that order was not chosen by the user.
Keeping that sorting step causes performance issues on larger databases, so removing it is preferable.
- Verified with Neptune Gremlin
- Resolves #1085
license.

Remove order by ID in fetch neighbors

---

packages/graph-explorer/src/connector/gremlin/fetchNeighbors/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/fetchNeighbors/oneHopTemplate.ts

Fixes a situation where the expand query would not return any edge results. The original query tried to use the vertex ID as a filter in the subquery for edges, but doesn't match properly when the ID type is UUID.
The solution actually simplifies the query a bit by naming the starting vertex `start`, updating the the neighbor name to `neighbor` for clarity, and changing the edge query to get all edges from `start` to any node in `neighbor`.
This removes the need for the ID to be injected in to the query in the edge part of the query.
```java
g.V("124").as("start")
.both()
.dedup()
.range(0, 10)
.as("neighbor")
.project("vertex", "edges")
.by()
.by(
__.select("start").bothE()
.where(otherV().where(eq("neighbor")))
.dedup().fold()
)
```
- Tested in Neptune with string IDs
- Tested in …

Fix expand neighbor query when edge ID is UUID

---

packages/graph-explorer/src/components/Dialog.tsx

Adjusted the styles for the `Dialog` and related components
* Removed gray background from dialog footer since it clashes with the default button style
* Adjusted layout of restricted width dialogs so all text is left aligned
* Fixed spacing between buttons within the `DialogFooter`
There was not an existing dialog that has two buttons, so I temporarily added one to the create prefix dialog to test out the styles.
* Buttons spaced apart properly
* Call to action on far right
* Buttons stack in reverse order so call to action is on top
* Part of #751 
license.

Adjust styles in DialogFooter

---

packages/graph-explorer/src/routes/Settings/LoadConfigButton.tsx

* Use DialogFooter in LoadConfigButton dialog
* Use default size buttons instead of large
* Changed error dialog button label to "Close" instead of "Cancel" since there is nothing to cancel
* Removed unnecessary `div` and styles
* Recommend to hide whitespace in GitHub file diff view
> [!NOTE]
> The footer will be white once PR #1147 goes in
- Part of #751
license.

Use DialogFooter in LoadConfigButton dialog

---

packages/shared/package.json
packages/shared/src/utils/testing/randomData.ts
pnpm-lock.yaml

* Remove use of `uuid` package for random string creation
* Use full range of numbers and lower case letters for random string, increasing the pool of possibilities
* Increase the count of random characters in the generated random string from 6 to 10
Ran test multiple times. Collisions were already super rare. This should make it ever more rare.
- Resolves #1149
license.

Increase randomness in generated test strings

---

packages/graph-explorer-proxy-server/src/error-handler.ts
packages/graph-explorer-proxy-server/src/logging.ts
packages/graph-explorer-proxy-server/src/node-server.ts
packages/graph-explorer-proxy-server/tsconfig.json

Use `verbatimModuleSyntax` as suggested by [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html?#im-compiling-and-running-the-outputs-in-nodejs)
* Built Docker image and ran locally
* N/A tech debt
license.

Use verbatimModuleSyntax in proxy server

---

packages/graph-explorer/src/core/StateProvider/graphSession/useRestoreGraphSession.ts

Fixed progress notification not being cleared when error is thrown during restoring of graph session. Moved notification clearing to `onSettled` callback and used useRef to hold notification ID.
Also removed the missleading comment in `onSettled` as the callback also get's called on error and does not only fire when the graph has been restored.
https://github.com/user-attachments/assets/57916140-feaf-462e-b406-61f4994c7e0b
Fixes #1154
license.

Clear graph restore progress notification

---

packages/graph-explorer/src/core/StateProvider/userPreferences.test.ts
packages/graph-explorer/src/core/StateProvider/userPreferences.ts
packages/graph-explorer/src/modules/NodesStyling/NodeStyleDialog.tsx
packages/graph-explorer/src/routes/DataExplorer/DataExplorer.tsx

This PR improves the input lag for the color pickers in both the `NodeStyleDialog` and the `EdgeStyleDialog` by implementing a helper function/hook `useDeferredAtom` as kindly suggested by @kmcginnes.
This function defers the actual updating of the atom state and allows for instant visual updates. 
The color updates on the canvas are happening much more rapidly than before and seem at least a little bit smoother.
Fixes #1104
license.

Fix input lag when changing node and edge colors

---

.github/workflows/unit.yml
.kiro/steering/tech.md
additionaldocs/development.md
package.json
pnpm-workspace.yaml

PNPM recently added a new feature to ensure a package reaches a certain minimum age before allowing it to be installed during an update.
* Updated to latest PNPM version 10.18
* Removed redundant engines entry in package.json since we rely on corepack
* Updated CI GitHub workflow
* Updated steering and other docs
* Added `minimumReleaseAge` setting to PNPM config
* Use PNPM and node version from `package.json` in CI build to keep the versions consistent
* [PNPM docs](https://pnpm.io/settings#minimumreleaseage)
* [PNPM release notes](https://pnpm.io/blog/releases/10.16#new-setting-for-delayed-dependency-updates)
* Local installation
* CI build
* Resolves #1196
license.

Reduce risk of malicious packages

---

packages/graph-explorer/src/modules/SearchSidebar/QuerySearchTabContent.tsx

Disables the spell checker, auto complete, and auto capitalization on the query editor text area.
* Tested in browser
* Resolves #1222
license.

Disable spell check, auto capitalize/complete
