.github/workflows/build_docker.yml

- Adding a manual trigger for the build_docker.yml workflow. Allows setting version tags for new releases.

Add manual trigger for ECR updates

---

docker-entrypoint.sh
packages/graph-explorer-proxy-server/cert-info/csr.conf

Cleans up the docker-entrypoint.sh and csr.conf file.

clean up csr.conf and docker-entrypoint.sh

---

.gitignore
THIRD_PARTY_LICENSES.txt
packages/graph-explorer-proxy-server/node-server.js
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
pnpm-lock.yaml

Issue #109
Updated various dependencies in order to avoid deprecations and warning error messages related to deprecations and outdated libs.

Issue 109 - Clean up docker build error messages

---

.gitignore
packages/graph-explorer-proxy-server/node-server.js
pnpm-lock.yaml

Added DS_Store to get gitignore, formatting code clean up.

---

Changelog.md

- Adding all commits in intermediate patch release 1.2.1 to the changelog.

Update changelog for release 1.2.1

---

README.md

- Update Default Connections documentation in README for openCypher and improved readability.

Reformat documentation for Default Connections

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Bump package version to 1.4.0

Release 1.4.0

---

Changelog.md
packages/graph-explorer/src/index.css

Issue #157 
I have updated the CSS styles to enable SVG rotation in a clockwise direction.

Fix spinner rotation

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Incrementing package version to 1.5.0.

Release 1.5.0

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Incrementing package version to 1.5.1

Release 1.5.1

---

.github/workflows/unit.yml

- Adds CI step `pnpm run types:check`
- Adds CI step `pnpm run lint:check`
- Adds CI step `pnpm run format:check`

Improve CI

---

packages/graph-explorer/src/components/icons/SyncIcon.tsx

Issue #, if available: #257
Mirrors the sync icon so that the arrows and rotation are consistent.

Flip the sync icon

---

additionaldocs/sagemaker/install-graph-explorer-lc.sh

Issue #, if available: #188
- Reinstated manual Proxy URL generation, as fallback for cases where the SageMaker `DescribeNotebookInstance` API call fails (ex. due to insufficient IAM permissions).

Improve Proxy URL generation in sample SageMaker lifecycle

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Incrementing package version to 1.6.0

Bump to 1.6.0

---

packages/graph-explorer/src/components/Tabular/Tabular.tsx
packages/graph-explorer/src/components/Tabular/TabularControlsProvider.tsx
packages/graph-explorer/src/components/Tabular/controls/ColumnSettingsControl/ColumnItem.tsx
packages/graph-explorer/src/components/Tabular/controls/ColumnSettingsControl/ExternalColumnSettingsControl.tsx
packages/graph-explorer/src/components/Tabular/controls/ExportControl/ExternalExportControl.tsx
packages/graph-explorer/src/components/Tabular/controls/ExportControl/transfomerToCsv.ts
packages/graph-explorer/src/components/Tabular/helpers/tableInstanceToTabularInstance.ts

This type error was happening because when we call the accessor to get the cell data for the row we could be passing either the row data or a wrapper object that contains the row data in one of its properties.
Since no logic required any of the data in the row wrapper, it made sense to move the check of what type of data we have up a level. So I added a new map before the big map logic to make sure we always have the row data and not the wrapper.
I updated the generic constraints across the board to match what React Table expects. This helped me find the issue with the row and row wrapper.
While these changes aren't necessary for the fix, I think they improve the code quality and will help find future issues.
This logic is super complicated and interwoven. I'd love to have it under some …

Fix CSV export

---

Dockerfile

This is a short term fix to make sure building a docker image works.
We will want the docker image to use CorePack going forward. But that will first require updating Node across the board, which will be a separate PR.
- Make sure docker is running
- Go to the root folder of the project and run:
```
docker build .
```
Relates to PR #305 and issue #303

Set PNPM version specifically

---

Changelog.md
additionaldocs/development.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

Preparation for the v1.7.0 release.
- Updated versions in all three `package.json` files
- Updated `Changelog.md`
- Updated `development.md`
- Addresses #368 
- Addresses #390
- Addresses #391

Release v1.7.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/workflows/build_docker.yml
.prettierignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Changelog.md
README.md
additionaldocs/README.md
additionaldocs/connections.md
additionaldocs/development.md
additionaldocs/ecs/ECS_FARGATE_DEPLOYMENT.md
additionaldocs/sagemaker/README.md
additionaldocs/sagemaker/graph-explorer-neptune-analytics-policy.json
additionaldocs/sagemaker/graph-explorer-neptune-db-policy.json
packages/graph-explorer-proxy-server/node-server.js

Remove nearly all items in the `.prettierignore` file so Prettier will format everything
- Visually inspect diffs
- Visually inspect Markdown files rendered in GitHub
- Addresses #327

Format everything

---

Changelog.md

Update the change log to read "Major Changes" instead of "Features" since there were no new features for this release.
- Check the spelling and grammar
- Parent #361 
- Related to #390 
license.

Change section title in Changelog

---

Changelog.md
packages/graph-explorer/src/modules/EntityDetails/EntityDetail.styles.ts
packages/graph-explorer/src/modules/EntityDetails/NodeDetail.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.styles.ts
packages/graph-explorer/src/modules/NodeExpand/NodeExpandContent.tsx
packages/graph-explorer/src/modules/common/VertexHeader.tsx

Refactors a few views in to simpler components to make the structure easier to understand.
No logic is actually changed. This is just moving some code around.
- Add a node and expand
- Change selection
- Show legend
- Part of #341 
- Part of #339
license.

Extract views to simpler components

---

packages/graph-explorer/src/modules/EntityDetails/EntityDetail.styles.ts

One of my prior PRs broke the styles in the edge details side panel. This fixes the styles.
- #339 
- #341 
license.

Fix edge detail styling

---

packages/graph-explorer/.eslintrc.json
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx

Extends the React hooks exhaustive dependencies rule to include Recoil `useRecoilCallback()`.
This found one issue.
- Create a connection
- #341 
- #339 
license.

More strict ESLint rules for Recoil

---

Changelog.md
package.json
pnpm-lock.yaml

TypeScript 5.5 was released recently. This PR updates us to the latest.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#inferred-type-predicates
- Verified with smoke test
license.

Update TypeScript to 5.5

---

packages/graph-explorer/src/connector/gremlin/templates/edgeLabelsTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/edgesSchemaTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/vertexLabelsTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/vertexTypeCountTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/verticesSchemaTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/verticesSchemaTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.test.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/hooks/useEntities.test.tsx
packages/graph-explorer/src/hooks/useNeighborsOptions.test.ts
packages/graph-explorer/src/hooks/useTextTransform.test.ts
packages/graph-explorer/src/modules/EntitiesFilter/useFiltersConfig.test.ts
packages/graph-explorer/src/modules/GraphViewer/renderNode.test.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.test.ts
packages/graph-explorer/src/utils/testing/index.ts
packages/graph-explorer/src/utils/testing/normalize.ts

There was not much to do as far as Gremlin optimizations. So I took the opportunity to cleanup the code a bit.
- Use function syntax
- Use `normalize` when it helps
- Add `normalizeWithNoSpace` as an alternative which is good for Gremlin queries
- Add `index.ts` for testing utils and fix imports
- Verified with quick smoke test
- Resolves #342 
- Resolves #380
license.

Gremlin cleanup

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/queries/__mock/should-return-all-neighbors-from-node-2018.json
packages/graph-explorer/src/connector/gremlin/queries/__mock/should-return-filtered-neighbors-from-node-2018.json
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighbors.test.ts
packages/graph-explorer/src/connector/gremlin/queries/fetchNeighbors.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.test.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/testUtils/globalMockFetch.ts

- Optimized the Gremlin query for fetching neighbors during node expansion
- Updated file based tests with new JSON response structure
- Mostly moved data around
- Only real change was to remove extra edges that the new query would not return
- Use ignore whitespace when reviewing
- Verified on Airports dataset
- Verified on large data set
- Resolves #380 
license.

Optimized neighbor query for Gremlin

---

Changelog.md
packages/graph-explorer/src/components/Tooltip/InfoTooltip.tsx
packages/graph-explorer/src/components/Tooltip/Tooltip.styles.ts
packages/graph-explorer/src/components/Tooltip/index.ts
packages/graph-explorer/src/components/icons/IconBase.tsx
packages/graph-explorer/src/components/index.ts
packages/graph-explorer/src/modules/CreateConnection/CreateConnection.tsx
packages/graph-explorer/src/modules/NodeExpand/NodeExpandFilters.tsx

- Fix `IconBase` color prop not being applied
- Improve `Tooltip` overlay padding
- Add new `InfoTooltip` component that combines the info icon and tooltip
- Centers properly vertically
- Uses text secondary color for icon color
- Icon is a tiny bit bigger than before
- Update connection modal to use new `InfoTooltip`
- Add new info tooltip to expand side bar for limit
- Resolves #461 
license.

Expand helper text

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Organize the change log to be more readable
- Update the version numbers across all `package.json` files
- #464
license.

Release v1.8.0 prep

---

packages/graph-explorer/src/modules/NodeExpand/NodeExpandFilters.tsx

Update helper text to read
> Please use full expansion if all the expected nodes are not returned from limited expansion
- #461 
license.

Updated helper text

---

packages/graph-explorer/src/components/Graph/internalComponents/EmptyState.tsx
packages/graph-explorer/src/components/Workspace/Workspace.styles.ts
packages/graph-explorer/src/components/Workspace/components/HideNavBarLogo.style.ts
packages/graph-explorer/src/components/Workspace/components/WorkspaceTopBar.tsx
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.styles.ts
packages/graph-explorer/src/modules/NodesStyling/SingleNodeStyling.style.ts
packages/graph-explorer/src/workspaces/Connections/Connections.styles.ts
packages/graph-explorer/src/workspaces/Connections/Connections.tsx
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.styles.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.styles.ts
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx

- Removed "Active" from "Active Connection: {connection name}"
- Use better flex CSS in top bar layout
- Utilize existing `title` and `subtitle` props for top nav
- When no active connection show "Connection: none" instead of "Connection: undefined"
- Update style of title and subtitle so it doesn't wrap
- Reduce spacing between logo and title
- Wrap text in graph empty state in a better way
- Add padding to graph empty state
- Fix inconsistent spacing between node and edge style sidebar panels
license.

Polish spacing

---

Changelog.md
THIRD_PARTY_LICENSES.txt
packages/graph-explorer/package.json
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/core/ConfigurationProvider/useConfiguration.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearchQuery.ts
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx
pnpm-lock.yaml

- Updated keyword search query to new style
- Use consistent query for both search and Data Explorer
- Reduce searches by ignoring changes to search attributes and exact match when no search term is provided
- Made limit explicit in search request
- Refactor Data Explorer component, breaking it down in to smaller pieces composed together
- Smoke test to make sure nothing breaks
- #340 
license.

Search query & Data Explorer

---

.github/workflows/unit.yml
Changelog.md
package.json

Fix the build by 
- Updating pnpm to v8.15.8
- Updating GitHub actions to latest versions
- Remove SHA from `package.json` pnpm version
license.

Update pnpm to latest v8 release

---

Changelog.md
packages/graph-explorer/src/components/PanelEmptyState/PanelEmptyState.styles.ts
packages/graph-explorer/src/components/PanelEmptyState/PanelEmptyState.tsx
packages/graph-explorer/src/components/PanelError.tsx
packages/graph-explorer/src/hooks/useSet.ts
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionDetail.tsx
packages/graph-explorer/src/modules/KeywordSearch/KeywordSearch.tsx
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearch.ts
packages/graph-explorer/src/modules/KeywordSearch/useKeywordSearchQuery.ts
packages/graph-explorer/src/modules/Namespaces/UserPrefixes.tsx
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

- Update `PanelEmptyState` styles around action
- Use default `PanelEmptyState` style for search loading
- Add `PanelError` for error case in search
- Split out search cancel action to a separate hook
- Removed destructuring of React Query object
* Added error state with retry
* Updated panel UI for loading
* Added empty state when no records
* Added error state with retry
Here are examples of the `PanelEmptyState` styles change.
- Slightly more space between title and subtitle
- Double the space between title/subtitle and button
- Default button style is `default`, so the old usages of action needed to pass `actionVariant="text"` to maintain their original style
- Resolves #340 
license.

Search & Data Explorer error UI

---

.eslintignore
.gitignore
.prettierignore
Changelog.md
Dockerfile
additionaldocs/development.md
docker-entrypoint.sh
package.json
packages/graph-explorer-proxy-server/node-server.ts
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer-proxy-server/tsconfig.json
packages/graph-explorer/.gitignore
packages/graph-explorer/package.json
pnpm-lock.yaml

- Convert proxy server to use TypeScript
- Change PNPM scripts to be consistent
- Run the dev environment `pnpm dev`
- Run the production environment `pnpm start`
- Run the production environment without the proxy server `pnpm start:client`
- Fix warnings in Docker build
- Update documentation
- Tested locally using dev environment
- Tested in local docker container
- Resolves #328
license.

Convert proxy server to TypeScript

---

Changelog.md
packages/graph-explorer/package.json
packages/graph-explorer/src/components/Carousel/Carousel.tsx
packages/graph-explorer/src/core/StateProvider/localForageEffect.ts
packages/graph-explorer/tsconfig.json
packages/graph-explorer/vite.config.ts
pnpm-lock.yaml

Updates Vite to latest v5 release
- Smoke test app
- Run `pnpm build`
- Resolves #496 
license.

Update Vite to latest

---

Dockerfile
package.json
packages/graph-explorer-proxy-server/logging.ts
packages/graph-explorer-proxy-server/node-server.ts
packages/graph-explorer-proxy-server/package.json
pnpm-lock.yaml

- Fix virtual path for Neptune Notebooks
- Add `LOG_STYLE` environment value for CloudWatch logs
- Add per request logging
- Update `pnpm start` to only run the proxy server to remove prefix on log statements
- Update pino to latest version
- Tested locally
license.

Logging formatting

---

Changelog.md
packages/graph-explorer-proxy-server/package.json
pnpm-lock.yaml

- Updates `@aws-sdk/credential-providers` to latest
- Updates `aws4` to latest
- Resolves #520
- CVE-2024-41818
license.

Update AWS SDK to fix security issue

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json

- Reorganize the release notes with different formatting and more information
- Update version numbers
- Best way to review the Changelog is to just read through the [updated rendered version](https://github.com/aws/graph-explorer/blob/5960c6795f215c78db4a4a1c9c95a813ef5c1c39/Changelog.md)
- Resolves #527 
license.

Release prep

---

Changelog.md
packages/graph-explorer/src/components/Button/Button.styles.ts
packages/graph-explorer/src/components/Button/Button.tsx
packages/graph-explorer/src/components/Typography.tsx
packages/graph-explorer/src/components/index.ts
packages/graph-explorer/src/core/AppErrorPage.tsx
packages/graph-explorer/src/core/AppLoadingPage.tsx
packages/graph-explorer/src/core/ConnectedProvider/ConnectedProvider.tsx
packages/graph-explorer/src/core/StateProvider/StateProvider.tsx
packages/graph-explorer/tailwind.config.ts

Adds an error boundary and a global error page for the app. This way, when it crashes it will at least show a friendly screen.
The screen has a reload button that will reload the entire page.
- Tested by throwing an explicit error from any component
- #546
license.

Error boundary suspense

---

README.md

Adds a minimum recommended versions section to the readme.
- Resolves #528 
license.

Add minimum recommended versions

---

Changelog.md
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer-proxy-server/src/error-handler.ts
packages/graph-explorer-proxy-server/src/logging.ts
packages/graph-explorer-proxy-server/src/node-server.ts
pnpm-lock.yaml

Abstracts and enhances the logging and error handling of the proxy server.
- Moves error handling logic to separate file
- Moves logging related logic to separate file
- Simplifies logging around errors
- Adds a simple 404 handler
- Fix issue in request logging middleware so that it captures the status after the request completes
- Added handler for SIGTERM to more gracefully shutdown
- Added handlers for unhandled exceptions and Promise rejections
- Adds zod to proxy server
- Verified with some manually thrown errors
- Verified 404 by hitting non-existent path
- Verified request logging gets proper status code
- Resolves #515 
- Resolves #511 
license.

Proxy server error handling and logging

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Bump the version to 1.10.0
- Reformat the change log to flow better
- Resolves #562 
- Resolves #561 
license.

Bump version & reformat changelog

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Bumped version to 1.10.1
- Organized changelog
license.

Bump version

---

Changelog.md
packages/graph-explorer/src/connector/gremlin/templates/edgesSchemaTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/gremlin/templates/verticesSchemaTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/openCypher/templates/oneHopTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/classWithCountsTemplates.ts
packages/graph-explorer/src/connector/sparql/templates/classesWithCountsTemplates.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/keywordSearch/keywordSearchTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/neighborsCount/blankNodeNeighborsCountTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/neighborsCount/neighborsCountTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighbors/blankNodeOneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighbors/oneHopNeighborsBlankNodesIdsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighbors/oneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/oneHopNeighborsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/predicatesByClassTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/predicatesWithCountsTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/subjectPredicates/blankNodeSubjectPredicatesTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/subjectPredicates/subjectPredicatesTemplate.ts
packages/graph-explorer/src/connector/sparql/templates/subjectPredicatesTemplate.ts
packages/graph-explorer/src/utils/index.ts
packages/graph-explorer/src/utils/sanitizeQuery.ts

Adds a custom `query` string template function that will run two operations on the string:
- `dedent` to remove leading space evenly across all lines
- regex to remove any empty lines
- Verified that queries in all three languages continue to work
license.

Add query sanitizer

---

packages/graph-explorer/src/core/ThemeProvider/themes/light.ts
packages/graph-explorer/src/index.css

The light & main variants of the success & error colors were reversed for the Tailwind theme. The only thing using any of those colors was the success check in the last modal of the "Load Configuration" flow. It now looks better than before.
- All styles look the same or better
license.

Fix error and success colors in Tailwind

---

Changelog.md
Dockerfile

The Docker image size has been creeping up recently. This change will reduce the image size by **196 MB** compared to the released version, or **327 MB** compared to the unreleased version in `main`.
| v1.10.1 | Unreleased `main` | This PR |
| - | - | - |
| 752 MB | 883 MB | 556 MB |
There were two changes that resulted in large size reductions:
- Combine all shell commands in to a single RUN step
- Remove PNPM store, which is a cache of NPM dependencies
Originally, the Dockerfile had a few different RUN commands with some configuration of environment values between them. In order to merge them I needed to use a different approach to the environment values.
There is a somewhat esoteric and unintuitive approach to conditional environment values that use variable expansion. It was detailed …

Reduce size of Docker image

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Update version numbers
- Reformat changelog
- None
- Part of #653 
license.

Release prep for v1.11.0

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Updates changelog for release
- Update version numbers to 1.12.0
- Smoke test locally
- #711 
license.

Release v1.12.0 prep

---

Changelog.md
packages/graph-explorer/package.json
packages/graph-explorer/src/App.tsx
packages/graph-explorer/src/components/Redirect.tsx
packages/graph-explorer/src/core/AppStatusLoader.tsx
packages/graph-explorer/src/index.tsx
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionData.tsx
packages/graph-explorer/src/workspaces/Connections/Connections.tsx
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx
packages/graph-explorer/src/workspaces/GraphExplorer/GraphExplorer.tsx
packages/graph-explorer/src/workspaces/Settings/SettingsRoot.tsx
pnpm-lock.yaml

React Router v7 provides some nice capabilities that we can tie in to for the URL sharing feature, as well as just generally.
This change only does the dependency update and minor code changes for the basic client side version. I am experimenting with the server side options in a different branch.
- Smoke tested locally
- Part of #719
license.

Update to React Router v7

---

Changelog.md
packages/graph-explorer/src/App.tsx
packages/graph-explorer/src/core/AppLoadingPage.tsx
packages/graph-explorer/src/core/AppStatusLoader.tsx
packages/graph-explorer/src/core/ConfigurationProvider/fetchConfiguration.ts
packages/graph-explorer/src/index.tsx
packages/graph-explorer/src/workspaces/Connections/Connections.tsx
packages/graph-explorer/vite.config.ts

Adds some logging and small improvements to the app bootstrapping process, specifically around config loading. This is born out of a bigger set of work regarding the default connection loading.
- Update `AppLoadingPage` to better match other startup loading screens, which makes the loading more consistent
- Adds debug logging to default connection fetch
- Adds debug logging to initial config load
- Adds debug logging to remote config fetch
- Adds proxy server to Vite config so that in dev mode requests to `/defaultConnection` go to the proxy server appropriately
- Basic formatting
- Verified locally with an empty database and a `defaultConnection.json` file
- Part of #634
license.

App loading and config loading

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Update the version to 1.13.0
- Update the changelog
- Smoke test locally
- Resolves #735 
license.

Release prep for version 1.13.0

---

additionaldocs/troubleshooting.md

This fixes a broken link in the documentation.
1. In the PR "Files changed" tab choose to open the markdown file directly
2. The link should work from there
license.

Fix link in documentation

---

Changelog.md
packages/graph-explorer/src/components/Tabular/builders/makeIconToggleCell.tsx
packages/graph-explorer/src/hooks/translations/gremlin-translations.json
packages/graph-explorer/src/hooks/translations/openCypher-translations.json
packages/graph-explorer/src/hooks/translations/sparql-translations.json
packages/graph-explorer/src/modules/ConnectionDetail/ConnectionData.tsx
packages/graph-explorer/src/modules/EntitiesTabular/components/EdgesTabular.tsx
packages/graph-explorer/src/modules/EntitiesTabular/components/NodesTabular.tsx
packages/graph-explorer/src/modules/SearchSidebar/FilterSearchTabContent.tsx

- Update all the places in the UI that reference "type" and change them to "label".
- Update the labels in the search sidebar to use the translation labels
- Update Table View header labels to be shorter to lower the chance of multi-line headers
- Fixes reference to empty message translation key in connection details panel
- Verified across Gremlin, openCypher, and SPARQL
- Resolves #748
- Resolves #757
license.

Update UI labels from "type" to "label"

---

Changelog.md
packages/graph-explorer/package.json
pnpm-lock.yaml

Remove some unused dependencies. Some of these are sub-dependencies of other dependencies, so they don't need to be in the `package.json`.
- Smoke test
license.

Remove unused dependencies

---

Changelog.md
README.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Update version to 1.14.0
- Update changelog to include a few paragraphs about the release
- Update the readme with better use of headline structure
- Add loading and saving a graph to the readme
- Resolves #784 
license.

Release prep v1.14

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Updates the changelog
- Bump version numbers to 1.14.1
- Smoke test locally
- Part of #817 
license.

Release prep for v1.14.1

---

packages/graph-explorer/vite.config.ts

Ignore test files in Vite to prevent hot module reload when tests change.
- Tested locally
license.

Don’t let test files cause a hot reload

---

packages/graph-explorer/tailwind.config.ts

Adds the ability to use `content-visibility` ([MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility)) to make large scrolling lists a bit more performant.
I use this in my implementation of the query editor coming in a future PR.
- No logic changed, just configuration
- Tested by applying to search result items and seeing the property in the chrome debug tools
- Tangentially related to #808
license.

Add content visibility to Tailwind

---

Changelog.md
packages/graph-explorer-proxy-server/src/node-server.ts
packages/graph-explorer/src/components/Button/Button.tsx
packages/graph-explorer/src/components/IconButton.tsx
packages/graph-explorer/src/connector/queries.ts
packages/graph-explorer/src/core/StateProvider/displayEdge.test.ts
packages/graph-explorer/src/index.css
packages/graph-explorer/src/modules/SearchSidebar/EdgeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/NodeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/QuerySearchTabContent.tsx
packages/graph-explorer/tailwind.config.ts

- Fix vertex and edge detail caching again (once more with feeling)
- Fix issue with search result add/remove button also expanding the result on click
- Adjust secondary text color to make placeholder text a bit more distinctive
- Use monospace font for query editor
- Add `TODO` for query cancellation not working right on the server
- Add screen reader text support in `IconButton`
- Add placeholder text in query editor
- Smoke tested locally
- Related to #808 
license.

Query editor small fixes

---

Changelog.md
package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Update version number to be 1.15.0
- Don't touch content of changelog yet since PRs still need to be merged
- Verified version is updated in UI
- Part of #816
license.

Bump version to 1.15.0

---

Changelog.md
README.md
samples/README.md
samples/air_routes/readme.md
samples/samples.md

- Updates changelog
- Adds summary of release
- Adds headings for change lists
- Reorder items
- Updates samples documentation
- Use `README.md` file name at each level to ensure GitHub renders the documentation properly
- Move link to samples in to the "Getting Started" section
- Add more copy to the samples landing page
- Add more structure to the Air Routes sample instructions
- Check grammar and spelling
- Check copy for valid content
- Part of #816 
license.

Update changelog for release

---

packages/graph-explorer/src/components/SelectField.tsx
packages/graph-explorer/src/components/Tabular/Tabular.tsx
packages/graph-explorer/src/components/Workspace/Workspace.tsx
packages/graph-explorer/src/components/Workspace/components/WorkspaceTopBar.tsx
packages/graph-explorer/src/connector/useGEFetchTypes.ts
packages/graph-explorer/src/core/StateProvider/displayAttribute.ts
packages/graph-explorer/src/core/StateProvider/displayEdge.test.ts
packages/graph-explorer/src/core/StateProvider/displayEdge.ts
packages/graph-explorer/src/hooks/useExpandNode.tsx
packages/graph-explorer/src/hooks/useNeighborsOptions.ts
packages/graph-explorer/src/modules/EntitiesTabular/components/NodesTabular.tsx
packages/graph-explorer/src/modules/GraphViewer/GraphViewer.tsx
packages/graph-explorer/src/modules/GraphViewer/internalComponents/ContextMenu.tsx
packages/graph-explorer/src/modules/GraphViewer/useGraphStyles.ts
packages/graph-explorer/src/modules/GraphViewer/useNodeBadges.ts
packages/graph-explorer/src/modules/Namespaces/GeneratedPrefixes.tsx
packages/graph-explorer/src/modules/Namespaces/UserPrefixes.tsx
packages/graph-explorer/src/modules/SearchSidebar/useKeywordSearch.test.ts
packages/graph-explorer/src/modules/common/NeighborsList/NeighborsList.tsx
packages/graph-explorer/src/workspaces/Connections/Connections.tsx
packages/graph-explorer/src/workspaces/DataExplorer/DataExplorer.tsx

After experimenting with a potentially useful ESLint plugin I discovered that it auto-fixed some of the imports in the project. I'm not quite ready to add the plugin to main as there are some issues to work out, but the import fix is worth keeping.
No logic changed. Only moving imports and combining duplicates.
- Smoke test
license.

Combine duplicate imports

---

packages/graph-explorer/src/components/EdgeRow.tsx
packages/graph-explorer/src/components/VertexRow.tsx

- Add 3 line clamp to title
- Change description clamp to 3 lines to match
- Verified in air routes with version type
| Before | After |
| ------ | ----- |
| ![CleanShot 2025-04-25 at 11 39 56@2x](https://github.com/user-attachments/assets/06335260-23dc-4657-91ad-17dce8495f49) | ![CleanShot 2025-04-25 at 11 39 42@2x](https://github.com/user-attachments/assets/ff11b672-433c-4101-a921-a4c8af5759cc) |
- Resolves #899 
license.

Set max lines for title and subtitle at 3 lines

---

Changelog.md
package.json
packages/graph-explorer/package.json
packages/shared/package.json

- Update changelog with summary of release
- Update module version numbers to 1.16.0
- Ensured version numbers are updated in UI
license.

Release v1.16 prep

---

Changelog.md
README.md
additionaldocs/features/README.md

- Moves feature descriptions to its own file: `/additionaldocs/features/README.md`
- Update link to roadmap
- Add smaller section in root readme that links to new features readme file
- No content changes to moved content other than title, roadmap link, and heading level
- Check content in new section
- Check links still work
- Part of #846 
license.

Move features docs to its own file

---

Changelog.md
package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

Updates the version numbers to v2.0.0.
I'll write up a few paragraphs about the release for the changelog in a separate PR.
- Ensured the version number displays in the UI
- Resolves #1001 
license.

Update version numbers to v2.0

---

Changelog.md

Adds a short writeup about the release.
- Check for grammar, misspellings, and inaccuracies
- Part of #1001 
license.

Add wrteup for release

---

Changelog.md

The [last PR merged](#1015) was merged after the release of v2.1. But the change log entry as in the 2.1 section, not a new 2.2 section.
- #992 
- #1015
license.

Fixes the changelog after the release

---

package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

Updates version to 2.2
- Made sure version shows in UI
- #1059
license.

Update version to 2.2

---

additionaldocs/troubleshooting.md

Adds a new section to the troubleshooting guide about mismatched proxy server URLs.
- N/A
- Resolves #894
license.

Add troubleshooting steps for mismatched proxy server

---

Changelog.md

Add release notes to the change log
- Checked grammar and spelling
- Part of #1059
license.

Update change log

---

ROADMAP.md

Updated roadmap reflecting the latest priority.
- Moved SPARQL query editor up in priority
- Introduced a Q4 2025 section to contain the items moved down
- Added callout styling for the disclaimer that the roadmap is subject to change
- Proof read
- N/A
license.

Updated roadmap

---

packages/graph-explorer/src/components/SearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/EdgeSearchResult.tsx
packages/graph-explorer/src/modules/SearchSidebar/VertexSearchResult.tsx

* Added border to signify when a node or edge is added to the graph
* Switched to ring instead of border for easier animations
https://github.com/user-attachments/assets/9fb4a1ad-b41b-442d-b5dc-f5e55b33e2ef
- Resolves #1098 
license.

Add highlight to nodes/edges added to the graph

---

package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

Bump version for patch release
- Ensured version number looks correct in UI
- N/A
license.

Bump version to 2.3.1 for patch

---

package.json
packages/graph-explorer-proxy-server/package.json
packages/graph-explorer/package.json
packages/shared/package.json

Bumps the version to v2.4.0
- Ensured version number looks correct in the app
- N/A
license.

Bump version to 2.4.0

---

.kiro/steering/documentation.md

Add Kiro steering doc to help with the creation and modification of documentation files.
* Used Kiro to generate some docs (other branch)
* Resolves #1163 
license.

Add steering doc for documentation

---

packages/graph-explorer-proxy-server/tsconfig.json

Update TypeScript compiler config for Node 24 according to TypeScript documentation.
* https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-24
* https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html?#im-compiling-and-running-the-outputs-in-nodejs
* Built docker image and ran locally to ensure TypeScript changes work
* N/A tech debt
license.

Update TypeScript config for Node 24

---

packages/graph-explorer/src/core/queryClient.ts
packages/graph-explorer/src/setupTests.ts

* Do not export `createDefaultOptions`
* Use inferred type for module in mock
* Ran the tests
* Resolves #1178 
* Helps with #1174
* Specifically: https://github.com/aws/graph-explorer/pull/1174/files#diff-9601a8f6c734c2001be34a2361f76946d19a39a709b5e8c624a2a5a0aade05f2R88
license.

Simplify queryClient test setup
